// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/api/internal/interfaces (interfaces: AgentService)

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	models "threadify-go/api/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockAgentService is a mock of AgentService interface.
type MockAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceMockRecorder
}

// MockAgentServiceMockRecorder is the mock recorder for MockAgentService.
type MockAgentServiceMockRecorder struct {
	mock *MockAgentService
}

// NewMockAgentService creates a new mock instance.
func NewMockAgentService(ctrl *gomock.Controller) *MockAgentService {
	mock := &MockAgentService{ctrl: ctrl}
	mock.recorder = &MockAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentService) EXPECT() *MockAgentServiceMockRecorder {
	return m.recorder
}

// ChatStream mocks base method.
func (m *MockAgentService) ChatStream(arg0 context.Context, arg1, arg2, arg3, arg4, arg5, arg6 string, arg7 models.StreamHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockAgentServiceMockRecorder) ChatStream(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockAgentService)(nil).ChatStream), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
}

// CheckCredits mocks base method.
func (m *MockAgentService) CheckCredits(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCredits", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCredits indicates an expected call of CheckCredits.
func (mr *MockAgentServiceMockRecorder) CheckCredits(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCredits", reflect.TypeOf((*MockAgentService)(nil).CheckCredits), arg0, arg1)
}

// ContinueConversation mocks base method.
func (m *MockAgentService) ContinueConversation(arg0 context.Context, arg1, arg2, arg3 string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContinueConversation", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ContinueConversation indicates an expected call of ContinueConversation.
func (mr *MockAgentServiceMockRecorder) ContinueConversation(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueConversation", reflect.TypeOf((*MockAgentService)(nil).ContinueConversation), arg0, arg1, arg2, arg3)
}

// DeleteConversation mocks base method.
func (m *MockAgentService) DeleteConversation(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversation indicates an expected call of DeleteConversation.
func (mr *MockAgentServiceMockRecorder) DeleteConversation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversation", reflect.TypeOf((*MockAgentService)(nil).DeleteConversation), arg0, arg1, arg2)
}

// GetConversations mocks base method.
func (m *MockAgentService) GetConversations(arg0 context.Context, arg1 string) ([]models.AgentConversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversations", arg0, arg1)
	ret0, _ := ret[0].([]models.AgentConversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversations indicates an expected call of GetConversations.
func (mr *MockAgentServiceMockRecorder) GetConversations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversations", reflect.TypeOf((*MockAgentService)(nil).GetConversations), arg0, arg1)
}

// GetMessagesForUser mocks base method.
func (m *MockAgentService) GetMessagesForUser(arg0 context.Context, arg1, arg2 string) ([]*models.AgentMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesForUser", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.AgentMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesForUser indicates an expected call of GetMessagesForUser.
func (mr *MockAgentServiceMockRecorder) GetMessagesForUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesForUser", reflect.TypeOf((*MockAgentService)(nil).GetMessagesForUser), arg0, arg1, arg2)
}
