// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/api/internal/domain (interfaces: TeamInvitationRepository)

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "threadify-go/api/internal/domain"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamInvitationRepository is a mock of TeamInvitationRepository interface.
type MockTeamInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamInvitationRepositoryMockRecorder
}

// MockTeamInvitationRepositoryMockRecorder is the mock recorder for MockTeamInvitationRepository.
type MockTeamInvitationRepositoryMockRecorder struct {
	mock *MockTeamInvitationRepository
}

// NewMockTeamInvitationRepository creates a new mock instance.
func NewMockTeamInvitationRepository(ctrl *gomock.Controller) *MockTeamInvitationRepository {
	mock := &MockTeamInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockTeamInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamInvitationRepository) EXPECT() *MockTeamInvitationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamInvitationRepository) Create(arg0 context.Context, arg1 *domain.TeamInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamInvitationRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamInvitationRepository)(nil).Create), arg0, arg1)
}

// CreateTx mocks base method.
func (m *MockTeamInvitationRepository) CreateTx(arg0 context.Context, arg1 domain.Execer, arg2 *domain.TeamInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockTeamInvitationRepositoryMockRecorder) CreateTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockTeamInvitationRepository)(nil).CreateTx), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockTeamInvitationRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamInvitationRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamInvitationRepository)(nil).Delete), arg0, arg1)
}

// DeleteExpired mocks base method.
func (m *MockTeamInvitationRepository) DeleteExpired(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockTeamInvitationRepositoryMockRecorder) DeleteExpired(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockTeamInvitationRepository)(nil).DeleteExpired), arg0)
}

// DeleteTx mocks base method.
func (m *MockTeamInvitationRepository) DeleteTx(arg0 context.Context, arg1 domain.Execer, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockTeamInvitationRepositoryMockRecorder) DeleteTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockTeamInvitationRepository)(nil).DeleteTx), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockTeamInvitationRepository) GetByID(arg0 context.Context, arg1 string) (*domain.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamInvitationRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamInvitationRepository)(nil).GetByID), arg0, arg1)
}

// GetByToken mocks base method.
func (m *MockTeamInvitationRepository) GetByToken(arg0 context.Context, arg1 string) (*domain.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", arg0, arg1)
	ret0, _ := ret[0].(*domain.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockTeamInvitationRepositoryMockRecorder) GetByToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockTeamInvitationRepository)(nil).GetByToken), arg0, arg1)
}

// GetPendingByCompanyAndEmail mocks base method.
func (m *MockTeamInvitationRepository) GetPendingByCompanyAndEmail(arg0 context.Context, arg1, arg2 string) (*domain.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingByCompanyAndEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingByCompanyAndEmail indicates an expected call of GetPendingByCompanyAndEmail.
func (mr *MockTeamInvitationRepositoryMockRecorder) GetPendingByCompanyAndEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingByCompanyAndEmail", reflect.TypeOf((*MockTeamInvitationRepository)(nil).GetPendingByCompanyAndEmail), arg0, arg1, arg2)
}

// ListByCompany mocks base method.
func (m *MockTeamInvitationRepository) ListByCompany(arg0 context.Context, arg1 string) ([]*domain.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCompany", arg0, arg1)
	ret0, _ := ret[0].([]*domain.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCompany indicates an expected call of ListByCompany.
func (mr *MockTeamInvitationRepositoryMockRecorder) ListByCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCompany", reflect.TypeOf((*MockTeamInvitationRepository)(nil).ListByCompany), arg0, arg1)
}

// MarkAccepted mocks base method.
func (m *MockTeamInvitationRepository) MarkAccepted(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccepted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccepted indicates an expected call of MarkAccepted.
func (mr *MockTeamInvitationRepositoryMockRecorder) MarkAccepted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccepted", reflect.TypeOf((*MockTeamInvitationRepository)(nil).MarkAccepted), arg0, arg1, arg2)
}

// MarkAcceptedTx mocks base method.
func (m *MockTeamInvitationRepository) MarkAcceptedTx(arg0 context.Context, arg1 domain.Execer, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAcceptedTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAcceptedTx indicates an expected call of MarkAcceptedTx.
func (mr *MockTeamInvitationRepositoryMockRecorder) MarkAcceptedTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAcceptedTx", reflect.TypeOf((*MockTeamInvitationRepository)(nil).MarkAcceptedTx), arg0, arg1, arg2, arg3)
}

// RefreshInvitation mocks base method.
func (m *MockTeamInvitationRepository) RefreshInvitation(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshInvitation", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshInvitation indicates an expected call of RefreshInvitation.
func (mr *MockTeamInvitationRepositoryMockRecorder) RefreshInvitation(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshInvitation", reflect.TypeOf((*MockTeamInvitationRepository)(nil).RefreshInvitation), arg0, arg1, arg2, arg3)
}

// UpdateStatus mocks base method.
func (m *MockTeamInvitationRepository) UpdateStatus(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTeamInvitationRepositoryMockRecorder) UpdateStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTeamInvitationRepository)(nil).UpdateStatus), arg0, arg1, arg2)
}
