// Code generated by MockGen. DO NOT EDIT.
// Source: usage_outbox_relay.go

// Package usageoutboxmocks is a generated GoMock package.
package usageoutboxmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	redis "github.com/redis/go-redis/v9"
)

// MockUsageOutboxPublisher is a mock of UsageOutboxPublisher interface.
type MockUsageOutboxPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockUsageOutboxPublisherMockRecorder
}

// MockUsageOutboxPublisherMockRecorder is the mock recorder for MockUsageOutboxPublisher.
type MockUsageOutboxPublisherMockRecorder struct {
	mock *MockUsageOutboxPublisher
}

// NewMockUsageOutboxPublisher creates a new mock instance.
func NewMockUsageOutboxPublisher(ctrl *gomock.Controller) *MockUsageOutboxPublisher {
	mock := &MockUsageOutboxPublisher{ctrl: ctrl}
	mock.recorder = &MockUsageOutboxPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageOutboxPublisher) EXPECT() *MockUsageOutboxPublisherMockRecorder {
	return m.recorder
}

// PublishCreditTopupTrigger mocks base method.
func (m *MockUsageOutboxPublisher) PublishCreditTopupTrigger(ctx context.Context, event map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCreditTopupTrigger", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCreditTopupTrigger indicates an expected call of PublishCreditTopupTrigger.
func (mr *MockUsageOutboxPublisherMockRecorder) PublishCreditTopupTrigger(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCreditTopupTrigger", reflect.TypeOf((*MockUsageOutboxPublisher)(nil).PublishCreditTopupTrigger), ctx, event)
}

// PublishUsageSyncBatch mocks base method.
func (m *MockUsageOutboxPublisher) PublishUsageSyncBatch(ctx context.Context, events []map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUsageSyncBatch", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUsageSyncBatch indicates an expected call of PublishUsageSyncBatch.
func (mr *MockUsageOutboxPublisherMockRecorder) PublishUsageSyncBatch(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUsageSyncBatch", reflect.TypeOf((*MockUsageOutboxPublisher)(nil).PublishUsageSyncBatch), ctx, events)
}

// MockUsageOutboxValkey is a mock of UsageOutboxValkey interface.
type MockUsageOutboxValkey struct {
	ctrl     *gomock.Controller
	recorder *MockUsageOutboxValkeyMockRecorder
}

// MockUsageOutboxValkeyMockRecorder is the mock recorder for MockUsageOutboxValkey.
type MockUsageOutboxValkeyMockRecorder struct {
	mock *MockUsageOutboxValkey
}

// NewMockUsageOutboxValkey creates a new mock instance.
func NewMockUsageOutboxValkey(ctrl *gomock.Controller) *MockUsageOutboxValkey {
	mock := &MockUsageOutboxValkey{ctrl: ctrl}
	mock.recorder = &MockUsageOutboxValkeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageOutboxValkey) EXPECT() *MockUsageOutboxValkeyMockRecorder {
	return m.recorder
}

// XAck mocks base method.
func (m *MockUsageOutboxValkey) XAck(ctx context.Context, stream, group string, ids ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, stream, group}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "XAck", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// XAck indicates an expected call of XAck.
func (mr *MockUsageOutboxValkeyMockRecorder) XAck(ctx, stream, group interface{}, ids ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, stream, group}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAck", reflect.TypeOf((*MockUsageOutboxValkey)(nil).XAck), varargs...)
}

// XGroupCreateMkStream mocks base method.
func (m *MockUsageOutboxValkey) XGroupCreateMkStream(ctx context.Context, stream, group, start string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XGroupCreateMkStream", ctx, stream, group, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// XGroupCreateMkStream indicates an expected call of XGroupCreateMkStream.
func (mr *MockUsageOutboxValkeyMockRecorder) XGroupCreateMkStream(ctx, stream, group, start interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XGroupCreateMkStream", reflect.TypeOf((*MockUsageOutboxValkey)(nil).XGroupCreateMkStream), ctx, stream, group, start)
}

// XReadGroup mocks base method.
func (m *MockUsageOutboxValkey) XReadGroup(ctx context.Context, args *redis.XReadGroupArgs) ([]redis.XStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XReadGroup", ctx, args)
	ret0, _ := ret[0].([]redis.XStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XReadGroup indicates an expected call of XReadGroup.
func (mr *MockUsageOutboxValkeyMockRecorder) XReadGroup(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XReadGroup", reflect.TypeOf((*MockUsageOutboxValkey)(nil).XReadGroup), ctx, args)
}

// MockUsageOutboxBatchForwarder is a mock of UsageOutboxBatchForwarder interface.
type MockUsageOutboxBatchForwarder struct {
	ctrl     *gomock.Controller
	recorder *MockUsageOutboxBatchForwarderMockRecorder
}

// MockUsageOutboxBatchForwarderMockRecorder is the mock recorder for MockUsageOutboxBatchForwarder.
type MockUsageOutboxBatchForwarderMockRecorder struct {
	mock *MockUsageOutboxBatchForwarder
}

// NewMockUsageOutboxBatchForwarder creates a new mock instance.
func NewMockUsageOutboxBatchForwarder(ctrl *gomock.Controller) *MockUsageOutboxBatchForwarder {
	mock := &MockUsageOutboxBatchForwarder{ctrl: ctrl}
	mock.recorder = &MockUsageOutboxBatchForwarderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageOutboxBatchForwarder) EXPECT() *MockUsageOutboxBatchForwarderMockRecorder {
	return m.recorder
}

// ForwardBatch mocks base method.
func (m *MockUsageOutboxBatchForwarder) ForwardBatch(ctx context.Context, streamStart string, block time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardBatch", ctx, streamStart, block)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForwardBatch indicates an expected call of ForwardBatch.
func (mr *MockUsageOutboxBatchForwarderMockRecorder) ForwardBatch(ctx, streamStart, block interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardBatch", reflect.TypeOf((*MockUsageOutboxBatchForwarder)(nil).ForwardBatch), ctx, streamStart, block)
}

// MockUsageOutboxSleeper is a mock of UsageOutboxSleeper interface.
type MockUsageOutboxSleeper struct {
	ctrl     *gomock.Controller
	recorder *MockUsageOutboxSleeperMockRecorder
}

// MockUsageOutboxSleeperMockRecorder is the mock recorder for MockUsageOutboxSleeper.
type MockUsageOutboxSleeperMockRecorder struct {
	mock *MockUsageOutboxSleeper
}

// NewMockUsageOutboxSleeper creates a new mock instance.
func NewMockUsageOutboxSleeper(ctrl *gomock.Controller) *MockUsageOutboxSleeper {
	mock := &MockUsageOutboxSleeper{ctrl: ctrl}
	mock.recorder = &MockUsageOutboxSleeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageOutboxSleeper) EXPECT() *MockUsageOutboxSleeperMockRecorder {
	return m.recorder
}

// Sleep mocks base method.
func (m *MockUsageOutboxSleeper) Sleep(ctx context.Context, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Sleep", ctx, d)
}

// Sleep indicates an expected call of Sleep.
func (mr *MockUsageOutboxSleeperMockRecorder) Sleep(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sleep", reflect.TypeOf((*MockUsageOutboxSleeper)(nil).Sleep), ctx, d)
}
