// Code generated by MockGen. DO NOT EDIT.
// Source: types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	jetstream "github.com/nats-io/nats.go/jetstream"
	archiver "github.com/threadify/engine/internal/archiver"
)

// MockDBExecer is a mock of DBExecer interface.
type MockDBExecer struct {
	ctrl     *gomock.Controller
	recorder *MockDBExecerMockRecorder
}

// MockDBExecerMockRecorder is the mock recorder for MockDBExecer.
type MockDBExecerMockRecorder struct {
	mock *MockDBExecer
}

// NewMockDBExecer creates a new mock instance.
func NewMockDBExecer(ctrl *gomock.Controller) *MockDBExecer {
	mock := &MockDBExecer{ctrl: ctrl}
	mock.recorder = &MockDBExecerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBExecer) EXPECT() *MockDBExecerMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDBExecer) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBExecerMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDBExecer)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockDBExecer) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBExecerMockRecorder) Exec(ctx, sql interface{}, arguments ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBExecer)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockDBExecer) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBExecerMockRecorder) Query(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBExecer)(nil).Query), varargs...)
}

// MockConsumerWriter is a mock of ConsumerWriter interface.
type MockConsumerWriter struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerWriterMockRecorder
}

// MockConsumerWriterMockRecorder is the mock recorder for MockConsumerWriter.
type MockConsumerWriterMockRecorder struct {
	mock *MockConsumerWriter
}

// NewMockConsumerWriter creates a new mock instance.
func NewMockConsumerWriter(ctrl *gomock.Controller) *MockConsumerWriter {
	mock := &MockConsumerWriter{ctrl: ctrl}
	mock.recorder = &MockConsumerWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerWriter) EXPECT() *MockConsumerWriterMockRecorder {
	return m.recorder
}

// SyncUsageMeters mocks base method.
func (m *MockConsumerWriter) SyncUsageMeters(ctx context.Context, events []archiver.UsageSyncEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUsageMeters", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUsageMeters indicates an expected call of SyncUsageMeters.
func (mr *MockConsumerWriterMockRecorder) SyncUsageMeters(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUsageMeters", reflect.TypeOf((*MockConsumerWriter)(nil).SyncUsageMeters), ctx, events)
}

// WriteActivityLog mocks base method.
func (m *MockConsumerWriter) WriteActivityLog(ctx context.Context, events []archiver.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteActivityLog", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteActivityLog indicates an expected call of WriteActivityLog.
func (mr *MockConsumerWriterMockRecorder) WriteActivityLog(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteActivityLog", reflect.TypeOf((*MockConsumerWriter)(nil).WriteActivityLog), ctx, events)
}

// WriteSubSteps mocks base method.
func (m *MockConsumerWriter) WriteSubSteps(ctx context.Context, subSteps []map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteSubSteps", ctx, subSteps)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteSubSteps indicates an expected call of WriteSubSteps.
func (mr *MockConsumerWriterMockRecorder) WriteSubSteps(ctx, subSteps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteSubSteps", reflect.TypeOf((*MockConsumerWriter)(nil).WriteSubSteps), ctx, subSteps)
}

// WriteThreadAccess mocks base method.
func (m *MockConsumerWriter) WriteThreadAccess(ctx context.Context, events []archiver.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteThreadAccess", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteThreadAccess indicates an expected call of WriteThreadAccess.
func (mr *MockConsumerWriterMockRecorder) WriteThreadAccess(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteThreadAccess", reflect.TypeOf((*MockConsumerWriter)(nil).WriteThreadAccess), ctx, events)
}

// WriteThreadMetadata mocks base method.
func (m *MockConsumerWriter) WriteThreadMetadata(ctx context.Context, events []archiver.StreamEvent) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteThreadMetadata", ctx, events)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteThreadMetadata indicates an expected call of WriteThreadMetadata.
func (mr *MockConsumerWriterMockRecorder) WriteThreadMetadata(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteThreadMetadata", reflect.TypeOf((*MockConsumerWriter)(nil).WriteThreadMetadata), ctx, events)
}

// WriteThreadNotifications mocks base method.
func (m *MockConsumerWriter) WriteThreadNotifications(ctx context.Context, events []archiver.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteThreadNotifications", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteThreadNotifications indicates an expected call of WriteThreadNotifications.
func (mr *MockConsumerWriterMockRecorder) WriteThreadNotifications(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteThreadNotifications", reflect.TypeOf((*MockConsumerWriter)(nil).WriteThreadNotifications), ctx, events)
}

// WriteThreadValidations mocks base method.
func (m *MockConsumerWriter) WriteThreadValidations(ctx context.Context, events []archiver.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteThreadValidations", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteThreadValidations indicates an expected call of WriteThreadValidations.
func (mr *MockConsumerWriterMockRecorder) WriteThreadValidations(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteThreadValidations", reflect.TypeOf((*MockConsumerWriter)(nil).WriteThreadValidations), ctx, events)
}

// MockJetStreamPublisher is a mock of JetStreamPublisher interface.
type MockJetStreamPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockJetStreamPublisherMockRecorder
}

// MockJetStreamPublisherMockRecorder is the mock recorder for MockJetStreamPublisher.
type MockJetStreamPublisherMockRecorder struct {
	mock *MockJetStreamPublisher
}

// NewMockJetStreamPublisher creates a new mock instance.
func NewMockJetStreamPublisher(ctrl *gomock.Controller) *MockJetStreamPublisher {
	mock := &MockJetStreamPublisher{ctrl: ctrl}
	mock.recorder = &MockJetStreamPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetStreamPublisher) EXPECT() *MockJetStreamPublisherMockRecorder {
	return m.recorder
}

// CreateOrUpdateConsumer mocks base method.
func (m *MockJetStreamPublisher) CreateOrUpdateConsumer(ctx context.Context, stream string, cfg jetstream.ConsumerConfig) (jetstream.Consumer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumer", ctx, stream, cfg)
	ret0, _ := ret[0].(jetstream.Consumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateConsumer indicates an expected call of CreateOrUpdateConsumer.
func (mr *MockJetStreamPublisherMockRecorder) CreateOrUpdateConsumer(ctx, stream, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumer", reflect.TypeOf((*MockJetStreamPublisher)(nil).CreateOrUpdateConsumer), ctx, stream, cfg)
}

// Publish mocks base method.
func (m *MockJetStreamPublisher) Publish(ctx context.Context, subject string, payload []byte, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, subject, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockJetStreamPublisherMockRecorder) Publish(ctx, subject, payload interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, subject, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockJetStreamPublisher)(nil).Publish), varargs...)
}
