billing:
  provider: stripe
  webhook_secret: "whsec_39a7f1c3d6fb6e5a638d8fa1d65d7b4589696b7067bbb7c14363e98cf1705848"
  secret_key: "sk_test_51TA9lg8bW3V5oRkWnrbloHeHpj1M847ZTaKeBi3DV4FUXFAGPmUFICekeQPjDfVIj4S3Vll9xJueuQQMXnALqtpx000WWSnW5r"
  success_url: "http://localhost:3000/success"
  cancel_url: "http://localhost:3000/cancel"

subscription:
  credit:
    ingress_cost_millicents: 100   # $1.00 per unit01 per unit
    egress_cost_millicents: 100      # $0.001 per MB
    seat_cost_millicents: 100               # $0.001 per seat
    contract_cost_millicents: 100             # $0.001 per contract
    rate_limit_tps: 600
    payload_limit_bytes: 1048576 # 1MB
