// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package sharedmocks is a generated GoMock package.
package sharedmocks

import (
	context "context"
	reflect "reflect"
	models "threadify-go/shared/models"

	gomock "github.com/golang/mock/gomock"
)

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// CreateCreditAccount mocks base method.
func (m *MockPlanRepository) CreateCreditAccount(ctx context.Context, account *models.CreditAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCreditAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCreditAccount indicates an expected call of CreateCreditAccount.
func (mr *MockPlanRepositoryMockRecorder) CreateCreditAccount(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCreditAccount", reflect.TypeOf((*MockPlanRepository)(nil).CreateCreditAccount), ctx, account)
}

// FindCompanyByExternalCustomerID mocks base method.
func (m *MockPlanRepository) FindCompanyByExternalCustomerID(ctx context.Context, externalCustomerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCompanyByExternalCustomerID", ctx, externalCustomerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCompanyByExternalCustomerID indicates an expected call of FindCompanyByExternalCustomerID.
func (mr *MockPlanRepositoryMockRecorder) FindCompanyByExternalCustomerID(ctx, externalCustomerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCompanyByExternalCustomerID", reflect.TypeOf((*MockPlanRepository)(nil).FindCompanyByExternalCustomerID), ctx, externalCustomerID)
}

// GetCreditAccount mocks base method.
func (m *MockPlanRepository) GetCreditAccount(ctx context.Context, companyID string) (*models.CreditAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreditAccount", ctx, companyID)
	ret0, _ := ret[0].(*models.CreditAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreditAccount indicates an expected call of GetCreditAccount.
func (mr *MockPlanRepositoryMockRecorder) GetCreditAccount(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreditAccount", reflect.TypeOf((*MockPlanRepository)(nil).GetCreditAccount), ctx, companyID)
}

// GetExternalCustomerID mocks base method.
func (m *MockPlanRepository) GetExternalCustomerID(ctx context.Context, companyID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalCustomerID", ctx, companyID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalCustomerID indicates an expected call of GetExternalCustomerID.
func (mr *MockPlanRepositoryMockRecorder) GetExternalCustomerID(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalCustomerID", reflect.TypeOf((*MockPlanRepository)(nil).GetExternalCustomerID), ctx, companyID)
}

// ListCompaniesForRollover mocks base method.
func (m *MockPlanRepository) ListCompaniesForRollover(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompaniesForRollover", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompaniesForRollover indicates an expected call of ListCompaniesForRollover.
func (mr *MockPlanRepositoryMockRecorder) ListCompaniesForRollover(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompaniesForRollover", reflect.TypeOf((*MockPlanRepository)(nil).ListCompaniesForRollover), ctx)
}

// SetExternalCustomerID mocks base method.
func (m *MockPlanRepository) SetExternalCustomerID(ctx context.Context, companyID, externalCustomerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExternalCustomerID", ctx, companyID, externalCustomerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExternalCustomerID indicates an expected call of SetExternalCustomerID.
func (mr *MockPlanRepositoryMockRecorder) SetExternalCustomerID(ctx, companyID, externalCustomerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExternalCustomerID", reflect.TypeOf((*MockPlanRepository)(nil).SetExternalCustomerID), ctx, companyID, externalCustomerID)
}

// UpdateCumulativeMonthlyCharge mocks base method.
func (m *MockPlanRepository) UpdateCumulativeMonthlyCharge(ctx context.Context, id string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCumulativeMonthlyCharge", ctx, id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCumulativeMonthlyCharge indicates an expected call of UpdateCumulativeMonthlyCharge.
func (mr *MockPlanRepositoryMockRecorder) UpdateCumulativeMonthlyCharge(ctx, id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCumulativeMonthlyCharge", reflect.TypeOf((*MockPlanRepository)(nil).UpdateCumulativeMonthlyCharge), ctx, id, amount)
}

// UpdateMaxMonthlyCharge mocks base method.
func (m *MockPlanRepository) UpdateMaxMonthlyCharge(ctx context.Context, companyID string, maxMonthlyMillicents int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaxMonthlyCharge", ctx, companyID, maxMonthlyMillicents)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaxMonthlyCharge indicates an expected call of UpdateMaxMonthlyCharge.
func (mr *MockPlanRepositoryMockRecorder) UpdateMaxMonthlyCharge(ctx, companyID, maxMonthlyMillicents interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaxMonthlyCharge", reflect.TypeOf((*MockPlanRepository)(nil).UpdateMaxMonthlyCharge), ctx, companyID, maxMonthlyMillicents)
}

// UpdateTopupSettings mocks base method.
func (m *MockPlanRepository) UpdateTopupSettings(ctx context.Context, companyID string, autoTopupAmount, minBalance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopupSettings", ctx, companyID, autoTopupAmount, minBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTopupSettings indicates an expected call of UpdateTopupSettings.
func (mr *MockPlanRepositoryMockRecorder) UpdateTopupSettings(ctx, companyID, autoTopupAmount, minBalance interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopupSettings", reflect.TypeOf((*MockPlanRepository)(nil).UpdateTopupSettings), ctx, companyID, autoTopupAmount, minBalance)
}

// MockEntityProfileTypeRepository is a mock of EntityProfileTypeRepository interface.
type MockEntityProfileTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntityProfileTypeRepositoryMockRecorder
}

// MockEntityProfileTypeRepositoryMockRecorder is the mock recorder for MockEntityProfileTypeRepository.
type MockEntityProfileTypeRepositoryMockRecorder struct {
	mock *MockEntityProfileTypeRepository
}

// NewMockEntityProfileTypeRepository creates a new mock instance.
func NewMockEntityProfileTypeRepository(ctrl *gomock.Controller) *MockEntityProfileTypeRepository {
	mock := &MockEntityProfileTypeRepository{ctrl: ctrl}
	mock.recorder = &MockEntityProfileTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityProfileTypeRepository) EXPECT() *MockEntityProfileTypeRepositoryMockRecorder {
	return m.recorder
}

// ArchiveProfileType mocks base method.
func (m *MockEntityProfileTypeRepository) ArchiveProfileType(ctx context.Context, companyID, profileTypeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveProfileType", ctx, companyID, profileTypeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveProfileType indicates an expected call of ArchiveProfileType.
func (mr *MockEntityProfileTypeRepositoryMockRecorder) ArchiveProfileType(ctx, companyID, profileTypeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveProfileType", reflect.TypeOf((*MockEntityProfileTypeRepository)(nil).ArchiveProfileType), ctx, companyID, profileTypeID)
}

// CreateProfileType mocks base method.
func (m *MockEntityProfileTypeRepository) CreateProfileType(ctx context.Context, profileType *models.EntityProfileType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfileType", ctx, profileType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfileType indicates an expected call of CreateProfileType.
func (mr *MockEntityProfileTypeRepositoryMockRecorder) CreateProfileType(ctx, profileType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfileType", reflect.TypeOf((*MockEntityProfileTypeRepository)(nil).CreateProfileType), ctx, profileType)
}

// GetProfileTypeByType mocks base method.
func (m *MockEntityProfileTypeRepository) GetProfileTypeByType(ctx context.Context, companyID, profileType string) (*models.EntityProfileType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileTypeByType", ctx, companyID, profileType)
	ret0, _ := ret[0].(*models.EntityProfileType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileTypeByType indicates an expected call of GetProfileTypeByType.
func (mr *MockEntityProfileTypeRepositoryMockRecorder) GetProfileTypeByType(ctx, companyID, profileType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileTypeByType", reflect.TypeOf((*MockEntityProfileTypeRepository)(nil).GetProfileTypeByType), ctx, companyID, profileType)
}

// GetProfileTypesByCompanyID mocks base method.
func (m *MockEntityProfileTypeRepository) GetProfileTypesByCompanyID(ctx context.Context, companyID string) ([]*models.EntityProfileType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileTypesByCompanyID", ctx, companyID)
	ret0, _ := ret[0].([]*models.EntityProfileType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileTypesByCompanyID indicates an expected call of GetProfileTypesByCompanyID.
func (mr *MockEntityProfileTypeRepositoryMockRecorder) GetProfileTypesByCompanyID(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileTypesByCompanyID", reflect.TypeOf((*MockEntityProfileTypeRepository)(nil).GetProfileTypesByCompanyID), ctx, companyID)
}

// UpdateProfileType mocks base method.
func (m *MockEntityProfileTypeRepository) UpdateProfileType(ctx context.Context, profileType *models.EntityProfileType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileType", ctx, profileType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfileType indicates an expected call of UpdateProfileType.
func (mr *MockEntityProfileTypeRepositoryMockRecorder) UpdateProfileType(ctx, profileType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileType", reflect.TypeOf((*MockEntityProfileTypeRepository)(nil).UpdateProfileType), ctx, profileType)
}

// MockEntityProfileRepository is a mock of EntityProfileRepository interface.
type MockEntityProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntityProfileRepositoryMockRecorder
}

// MockEntityProfileRepositoryMockRecorder is the mock recorder for MockEntityProfileRepository.
type MockEntityProfileRepositoryMockRecorder struct {
	mock *MockEntityProfileRepository
}

// NewMockEntityProfileRepository creates a new mock instance.
func NewMockEntityProfileRepository(ctrl *gomock.Controller) *MockEntityProfileRepository {
	mock := &MockEntityProfileRepository{ctrl: ctrl}
	mock.recorder = &MockEntityProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityProfileRepository) EXPECT() *MockEntityProfileRepositoryMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockEntityProfileRepository) CreateProfile(ctx context.Context, profile *models.EntityProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockEntityProfileRepositoryMockRecorder) CreateProfile(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockEntityProfileRepository)(nil).CreateProfile), ctx, profile)
}

// GetProfileByIDWithMetrics mocks base method.
func (m *MockEntityProfileRepository) GetProfileByIDWithMetrics(ctx context.Context, companyID, entityProfileID string) (*models.EntityProfile, *models.EntityProfileMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByIDWithMetrics", ctx, companyID, entityProfileID)
	ret0, _ := ret[0].(*models.EntityProfile)
	ret1, _ := ret[1].(*models.EntityProfileMetrics)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfileByIDWithMetrics indicates an expected call of GetProfileByIDWithMetrics.
func (mr *MockEntityProfileRepositoryMockRecorder) GetProfileByIDWithMetrics(ctx, companyID, entityProfileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByIDWithMetrics", reflect.TypeOf((*MockEntityProfileRepository)(nil).GetProfileByIDWithMetrics), ctx, companyID, entityProfileID)
}

// GetProfileByRefKey mocks base method.
func (m *MockEntityProfileRepository) GetProfileByRefKey(ctx context.Context, companyID, profileTypeID, refKey string) (*models.EntityProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByRefKey", ctx, companyID, profileTypeID, refKey)
	ret0, _ := ret[0].(*models.EntityProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByRefKey indicates an expected call of GetProfileByRefKey.
func (mr *MockEntityProfileRepositoryMockRecorder) GetProfileByRefKey(ctx, companyID, profileTypeID, refKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByRefKey", reflect.TypeOf((*MockEntityProfileRepository)(nil).GetProfileByRefKey), ctx, companyID, profileTypeID, refKey)
}

// GetProfileMetrics mocks base method.
func (m *MockEntityProfileRepository) GetProfileMetrics(ctx context.Context, entityProfileID string) (*models.EntityProfileMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileMetrics", ctx, entityProfileID)
	ret0, _ := ret[0].(*models.EntityProfileMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileMetrics indicates an expected call of GetProfileMetrics.
func (mr *MockEntityProfileRepositoryMockRecorder) GetProfileMetrics(ctx, entityProfileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileMetrics", reflect.TypeOf((*MockEntityProfileRepository)(nil).GetProfileMetrics), ctx, entityProfileID)
}

// GetProfileWithMetrics mocks base method.
func (m *MockEntityProfileRepository) GetProfileWithMetrics(ctx context.Context, companyID, typeName, refKey string) (*models.EntityProfile, *models.EntityProfileMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileWithMetrics", ctx, companyID, typeName, refKey)
	ret0, _ := ret[0].(*models.EntityProfile)
	ret1, _ := ret[1].(*models.EntityProfileMetrics)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProfileWithMetrics indicates an expected call of GetProfileWithMetrics.
func (mr *MockEntityProfileRepositoryMockRecorder) GetProfileWithMetrics(ctx, companyID, typeName, refKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileWithMetrics", reflect.TypeOf((*MockEntityProfileRepository)(nil).GetProfileWithMetrics), ctx, companyID, typeName, refKey)
}
