// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/api/internal/interfaces (interfaces: TeamInvitationService)

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	models "threadify-go/api/internal/models"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamInvitationService is a mock of TeamInvitationService interface.
type MockTeamInvitationService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamInvitationServiceMockRecorder
}

// MockTeamInvitationServiceMockRecorder is the mock recorder for MockTeamInvitationService.
type MockTeamInvitationServiceMockRecorder struct {
	mock *MockTeamInvitationService
}

// NewMockTeamInvitationService creates a new mock instance.
func NewMockTeamInvitationService(ctrl *gomock.Controller) *MockTeamInvitationService {
	mock := &MockTeamInvitationService{ctrl: ctrl}
	mock.recorder = &MockTeamInvitationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamInvitationService) EXPECT() *MockTeamInvitationServiceMockRecorder {
	return m.recorder
}

// CancelInvitation mocks base method.
func (m *MockTeamInvitationService) CancelInvitation(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInvitation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelInvitation indicates an expected call of CancelInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) CancelInvitation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).CancelInvitation), arg0, arg1)
}

// GetByCompanyAndEmail mocks base method.
func (m *MockTeamInvitationService) GetByCompanyAndEmail(arg0 context.Context, arg1, arg2 string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCompanyAndEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCompanyAndEmail indicates an expected call of GetByCompanyAndEmail.
func (mr *MockTeamInvitationServiceMockRecorder) GetByCompanyAndEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCompanyAndEmail", reflect.TypeOf((*MockTeamInvitationService)(nil).GetByCompanyAndEmail), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockTeamInvitationService) GetByID(arg0 context.Context, arg1 string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamInvitationServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamInvitationService)(nil).GetByID), arg0, arg1)
}

// ListByCompany mocks base method.
func (m *MockTeamInvitationService) ListByCompany(arg0 context.Context, arg1 string) ([]*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCompany", arg0, arg1)
	ret0, _ := ret[0].([]*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCompany indicates an expected call of ListByCompany.
func (mr *MockTeamInvitationServiceMockRecorder) ListByCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCompany", reflect.TypeOf((*MockTeamInvitationService)(nil).ListByCompany), arg0, arg1)
}

// MarkAccepted mocks base method.
func (m *MockTeamInvitationService) MarkAccepted(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccepted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccepted indicates an expected call of MarkAccepted.
func (mr *MockTeamInvitationServiceMockRecorder) MarkAccepted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccepted", reflect.TypeOf((*MockTeamInvitationService)(nil).MarkAccepted), arg0, arg1, arg2)
}

// RefreshInvitation mocks base method.
func (m *MockTeamInvitationService) RefreshInvitation(arg0 context.Context, arg1 *models.TeamInvitation, arg2 time.Duration) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshInvitation", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshInvitation indicates an expected call of RefreshInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) RefreshInvitation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).RefreshInvitation), arg0, arg1, arg2)
}

// SendInvitation mocks base method.
func (m *MockTeamInvitationService) SendInvitation(arg0 context.Context, arg1, arg2, arg3, arg4 string, arg5 time.Duration) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvitation", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendInvitation indicates an expected call of SendInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) SendInvitation(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).SendInvitation), arg0, arg1, arg2, arg3, arg4, arg5)
}

// ValidateToken mocks base method.
func (m *MockTeamInvitationService) ValidateToken(arg0 context.Context, arg1 string) (*models.ValidateTokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0, arg1)
	ret0, _ := ret[0].(*models.ValidateTokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTeamInvitationServiceMockRecorder) ValidateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTeamInvitationService)(nil).ValidateToken), arg0, arg1)
}
