// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/shared/billing (interfaces: PlanService)

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"
	domain "threadify-go/shared/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockPlanService is a mock of PlanService interface.
type MockPlanService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanServiceMockRecorder
}

// MockPlanServiceMockRecorder is the mock recorder for MockPlanService.
type MockPlanServiceMockRecorder struct {
	mock *MockPlanService
}

// NewMockPlanService creates a new mock instance.
func NewMockPlanService(ctrl *gomock.Controller) *MockPlanService {
	mock := &MockPlanService{ctrl: ctrl}
	mock.recorder = &MockPlanServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanService) EXPECT() *MockPlanServiceMockRecorder {
	return m.recorder
}

// ChargeContract mocks base method.
func (m *MockPlanService) ChargeContract(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChargeContract", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChargeContract indicates an expected call of ChargeContract.
func (mr *MockPlanServiceMockRecorder) ChargeContract(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChargeContract", reflect.TypeOf((*MockPlanService)(nil).ChargeContract), arg0, arg1)
}

// ChargeContractVersion mocks base method.
func (m *MockPlanService) ChargeContractVersion(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChargeContractVersion", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChargeContractVersion indicates an expected call of ChargeContractVersion.
func (mr *MockPlanServiceMockRecorder) ChargeContractVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChargeContractVersion", reflect.TypeOf((*MockPlanService)(nil).ChargeContractVersion), arg0, arg1)
}

// CheckBalancePositive mocks base method.
func (m *MockPlanService) CheckBalancePositive(arg0 context.Context, arg1 string) (*domain.CreditAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBalancePositive", arg0, arg1)
	ret0, _ := ret[0].(*domain.CreditAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBalancePositive indicates an expected call of CheckBalancePositive.
func (mr *MockPlanServiceMockRecorder) CheckBalancePositive(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBalancePositive", reflect.TypeOf((*MockPlanService)(nil).CheckBalancePositive), arg0, arg1)
}

// CheckCreditAvailable mocks base method.
func (m *MockPlanService) CheckCreditAvailable(arg0 context.Context, arg1, arg2 string, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCreditAvailable", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckCreditAvailable indicates an expected call of CheckCreditAvailable.
func (mr *MockPlanServiceMockRecorder) CheckCreditAvailable(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCreditAvailable", reflect.TypeOf((*MockPlanService)(nil).CheckCreditAvailable), arg0, arg1, arg2, arg3)
}

// CheckPayloadSize mocks base method.
func (m *MockPlanService) CheckPayloadSize(arg0 context.Context, arg1 *domain.CreditAccount, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPayloadSize", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPayloadSize indicates an expected call of CheckPayloadSize.
func (mr *MockPlanServiceMockRecorder) CheckPayloadSize(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPayloadSize", reflect.TypeOf((*MockPlanService)(nil).CheckPayloadSize), arg0, arg1, arg2)
}

// DecrementEgress mocks base method.
func (m *MockPlanService) DecrementEgress(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementEgress", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementEgress indicates an expected call of DecrementEgress.
func (mr *MockPlanServiceMockRecorder) DecrementEgress(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementEgress", reflect.TypeOf((*MockPlanService)(nil).DecrementEgress), arg0, arg1, arg2)
}

// DecrementIngress mocks base method.
func (m *MockPlanService) DecrementIngress(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementIngress", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementIngress indicates an expected call of DecrementIngress.
func (mr *MockPlanServiceMockRecorder) DecrementIngress(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementIngress", reflect.TypeOf((*MockPlanService)(nil).DecrementIngress), arg0, arg1, arg2)
}

// DecrementLLMUsage mocks base method.
func (m *MockPlanService) DecrementLLMUsage(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementLLMUsage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementLLMUsage indicates an expected call of DecrementLLMUsage.
func (mr *MockPlanServiceMockRecorder) DecrementLLMUsage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementLLMUsage", reflect.TypeOf((*MockPlanService)(nil).DecrementLLMUsage), arg0, arg1, arg2)
}

// GetCurrentLimits mocks base method.
func (m *MockPlanService) GetCurrentLimits(arg0 context.Context, arg1 string) (*domain.CreditAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentLimits", arg0, arg1)
	ret0, _ := ret[0].(*domain.CreditAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentLimits indicates an expected call of GetCurrentLimits.
func (mr *MockPlanServiceMockRecorder) GetCurrentLimits(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentLimits", reflect.TypeOf((*MockPlanService)(nil).GetCurrentLimits), arg0, arg1)
}

// GetExternalCustomerID mocks base method.
func (m *MockPlanService) GetExternalCustomerID(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalCustomerID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalCustomerID indicates an expected call of GetExternalCustomerID.
func (mr *MockPlanServiceMockRecorder) GetExternalCustomerID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalCustomerID", reflect.TypeOf((*MockPlanService)(nil).GetExternalCustomerID), arg0, arg1)
}

// InvalidatePlanCache mocks base method.
func (m *MockPlanService) InvalidatePlanCache(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidatePlanCache", arg0, arg1)
}

// InvalidatePlanCache indicates an expected call of InvalidatePlanCache.
func (mr *MockPlanServiceMockRecorder) InvalidatePlanCache(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidatePlanCache", reflect.TypeOf((*MockPlanService)(nil).InvalidatePlanCache), arg0, arg1)
}

// ProcessRollovers mocks base method.
func (m *MockPlanService) ProcessRollovers(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRollovers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessRollovers indicates an expected call of ProcessRollovers.
func (mr *MockPlanServiceMockRecorder) ProcessRollovers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRollovers", reflect.TypeOf((*MockPlanService)(nil).ProcessRollovers), arg0)
}

// ProvisionSubscription mocks base method.
func (m *MockPlanService) ProvisionSubscription(arg0 context.Context, arg1, arg2 string, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionSubscription", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProvisionSubscription indicates an expected call of ProvisionSubscription.
func (mr *MockPlanServiceMockRecorder) ProvisionSubscription(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionSubscription", reflect.TypeOf((*MockPlanService)(nil).ProvisionSubscription), arg0, arg1, arg2, arg3)
}
