// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"
	models0 "threadify-go/shared/models"
	time "time"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/threadify/engine/internal/interfaces"
	models "github.com/threadify/engine/internal/models"
)

// MockContractRepository is a mock of ContractRepository interface.
type MockContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractRepositoryMockRecorder
}

// MockContractRepositoryMockRecorder is the mock recorder for MockContractRepository.
type MockContractRepositoryMockRecorder struct {
	mock *MockContractRepository
}

// NewMockContractRepository creates a new mock instance.
func NewMockContractRepository(ctrl *gomock.Controller) *MockContractRepository {
	mock := &MockContractRepository{ctrl: ctrl}
	mock.recorder = &MockContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractRepository) EXPECT() *MockContractRepositoryMockRecorder {
	return m.recorder
}

// CountByCompany mocks base method.
func (m *MockContractRepository) CountByCompany(ctx context.Context, companyID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCompany", ctx, companyID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCompany indicates an expected call of CountByCompany.
func (mr *MockContractRepositoryMockRecorder) CountByCompany(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCompany", reflect.TypeOf((*MockContractRepository)(nil).CountByCompany), ctx, companyID)
}

// Create mocks base method.
func (m *MockContractRepository) Create(ctx context.Context, contract *models.Contract) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContractRepositoryMockRecorder) Create(ctx, contract interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContractRepository)(nil).Create), ctx, contract)
}

// CreateContractWithVersion mocks base method.
func (m *MockContractRepository) CreateContractWithVersion(ctx context.Context, contract *models.Contract, version *models.ContractVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContractWithVersion", ctx, contract, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContractWithVersion indicates an expected call of CreateContractWithVersion.
func (mr *MockContractRepositoryMockRecorder) CreateContractWithVersion(ctx, contract, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContractWithVersion", reflect.TypeOf((*MockContractRepository)(nil).CreateContractWithVersion), ctx, contract, version)
}

// CreateVersion mocks base method.
func (m *MockContractRepository) CreateVersion(ctx context.Context, v *models.ContractVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockContractRepositoryMockRecorder) CreateVersion(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockContractRepository)(nil).CreateVersion), ctx, v)
}

// Get mocks base method.
func (m *MockContractRepository) Get(ctx context.Context, id string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContractRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContractRepository)(nil).Get), ctx, id)
}

// GetAllByOwner mocks base method.
func (m *MockContractRepository) GetAllByOwner(ctx context.Context, ownerID string) ([]*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByOwner", ctx, ownerID)
	ret0, _ := ret[0].([]*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByOwner indicates an expected call of GetAllByOwner.
func (mr *MockContractRepositoryMockRecorder) GetAllByOwner(ctx, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByOwner", reflect.TypeOf((*MockContractRepository)(nil).GetAllByOwner), ctx, ownerID)
}

// GetAllVersions mocks base method.
func (m *MockContractRepository) GetAllVersions(ctx context.Context, contractID string) ([]*models.ContractVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllVersions", ctx, contractID)
	ret0, _ := ret[0].([]*models.ContractVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllVersions indicates an expected call of GetAllVersions.
func (mr *MockContractRepositoryMockRecorder) GetAllVersions(ctx, contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllVersions", reflect.TypeOf((*MockContractRepository)(nil).GetAllVersions), ctx, contractID)
}

// GetByID mocks base method.
func (m *MockContractRepository) GetByID(ctx context.Context, contractID string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, contractID)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockContractRepositoryMockRecorder) GetByID(ctx, contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockContractRepository)(nil).GetByID), ctx, contractID)
}

// GetByIDAndOwner mocks base method.
func (m *MockContractRepository) GetByIDAndOwner(ctx context.Context, contractID, ownerID string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndOwner", ctx, contractID, ownerID)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndOwner indicates an expected call of GetByIDAndOwner.
func (mr *MockContractRepositoryMockRecorder) GetByIDAndOwner(ctx, contractID, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndOwner", reflect.TypeOf((*MockContractRepository)(nil).GetByIDAndOwner), ctx, contractID, ownerID)
}

// GetByName mocks base method.
func (m *MockContractRepository) GetByName(ctx context.Context, name string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockContractRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockContractRepository)(nil).GetByName), ctx, name)
}

// GetByNameAndCompany mocks base method.
func (m *MockContractRepository) GetByNameAndCompany(ctx context.Context, name, companyID string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameAndCompany", ctx, name, companyID)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameAndCompany indicates an expected call of GetByNameAndCompany.
func (mr *MockContractRepositoryMockRecorder) GetByNameAndCompany(ctx, name, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameAndCompany", reflect.TypeOf((*MockContractRepository)(nil).GetByNameAndCompany), ctx, name, companyID)
}

// GetByNameSlim mocks base method.
func (m *MockContractRepository) GetByNameSlim(ctx context.Context, name string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameSlim", ctx, name)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameSlim indicates an expected call of GetByNameSlim.
func (mr *MockContractRepositoryMockRecorder) GetByNameSlim(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameSlim", reflect.TypeOf((*MockContractRepository)(nil).GetByNameSlim), ctx, name)
}

// GetLatestVersion mocks base method.
func (m *MockContractRepository) GetLatestVersion(ctx context.Context, contractID string) (*models.ContractVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", ctx, contractID)
	ret0, _ := ret[0].(*models.ContractVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockContractRepositoryMockRecorder) GetLatestVersion(ctx, contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockContractRepository)(nil).GetLatestVersion), ctx, contractID)
}

// GetVersion mocks base method.
func (m *MockContractRepository) GetVersion(ctx context.Context, contractID string, version int) (*models.ContractVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, contractID, version)
	ret0, _ := ret[0].(*models.ContractVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockContractRepositoryMockRecorder) GetVersion(ctx, contractID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockContractRepository)(nil).GetVersion), ctx, contractID, version)
}

// SoftDelete mocks base method.
func (m *MockContractRepository) SoftDelete(ctx context.Context, contractID string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, contractID, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockContractRepositoryMockRecorder) SoftDelete(ctx, contractID, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockContractRepository)(nil).SoftDelete), ctx, contractID, updatedAt)
}

// SoftDeleteVersion mocks base method.
func (m *MockContractRepository) SoftDeleteVersion(ctx context.Context, contractID string, version int, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteVersion", ctx, contractID, version, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteVersion indicates an expected call of SoftDeleteVersion.
func (mr *MockContractRepositoryMockRecorder) SoftDeleteVersion(ctx, contractID, version, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteVersion", reflect.TypeOf((*MockContractRepository)(nil).SoftDeleteVersion), ctx, contractID, version, updatedAt)
}

// Update mocks base method.
func (m *MockContractRepository) Update(ctx context.Context, contractID, description, contentHash string, latestVersion int, updatedAt time.Time) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, contractID, description, contentHash, latestVersion, updatedAt)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockContractRepositoryMockRecorder) Update(ctx, contractID, description, contentHash, latestVersion, updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContractRepository)(nil).Update), ctx, contractID, description, contentHash, latestVersion, updatedAt)
}

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// GetUserRoles mocks base method.
func (m *MockAuthRepository) GetUserRoles(ctx context.Context, principalID, principalType string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, principalID, principalType)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAuthRepositoryMockRecorder) GetUserRoles(ctx, principalID, principalType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAuthRepository)(nil).GetUserRoles), ctx, principalID, principalType)
}

// ValidateAPIKey mocks base method.
func (m *MockAuthRepository) ValidateAPIKey(ctx context.Context, keyHash string) (*models.AuthInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAPIKey", ctx, keyHash)
	ret0, _ := ret[0].(*models.AuthInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAPIKey indicates an expected call of ValidateAPIKey.
func (mr *MockAuthRepositoryMockRecorder) ValidateAPIKey(ctx, keyHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAPIKey", reflect.TypeOf((*MockAuthRepository)(nil).ValidateAPIKey), ctx, keyHash)
}

// MockActorRepository is a mock of ActorRepository interface.
type MockActorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorRepositoryMockRecorder
}

// MockActorRepositoryMockRecorder is the mock recorder for MockActorRepository.
type MockActorRepositoryMockRecorder struct {
	mock *MockActorRepository
}

// NewMockActorRepository creates a new mock instance.
func NewMockActorRepository(ctrl *gomock.Controller) *MockActorRepository {
	mock := &MockActorRepository{ctrl: ctrl}
	mock.recorder = &MockActorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorRepository) EXPECT() *MockActorRepositoryMockRecorder {
	return m.recorder
}

// ResolveActors mocks base method.
func (m *MockActorRepository) ResolveActors(ctx context.Context, ids []string) ([]*models.ActorInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveActors", ctx, ids)
	ret0, _ := ret[0].([]*models.ActorInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveActors indicates an expected call of ResolveActors.
func (mr *MockActorRepositoryMockRecorder) ResolveActors(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveActors", reflect.TypeOf((*MockActorRepository)(nil).ResolveActors), ctx, ids)
}

// MockBillingRepository is a mock of BillingRepository interface.
type MockBillingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillingRepositoryMockRecorder
}

// MockBillingRepositoryMockRecorder is the mock recorder for MockBillingRepository.
type MockBillingRepositoryMockRecorder struct {
	mock *MockBillingRepository
}

// NewMockBillingRepository creates a new mock instance.
func NewMockBillingRepository(ctrl *gomock.Controller) *MockBillingRepository {
	mock := &MockBillingRepository{ctrl: ctrl}
	mock.recorder = &MockBillingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingRepository) EXPECT() *MockBillingRepositoryMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockBillingRepository) CreateSnapshot(ctx context.Context, snapshot *models0.BillingSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockBillingRepositoryMockRecorder) CreateSnapshot(ctx, snapshot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockBillingRepository)(nil).CreateSnapshot), ctx, snapshot)
}

// FindSnapshotByInvoiceID mocks base method.
func (m *MockBillingRepository) FindSnapshotByInvoiceID(ctx context.Context, externalInvoiceID string) (*models0.BillingSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSnapshotByInvoiceID", ctx, externalInvoiceID)
	ret0, _ := ret[0].(*models0.BillingSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSnapshotByInvoiceID indicates an expected call of FindSnapshotByInvoiceID.
func (mr *MockBillingRepositoryMockRecorder) FindSnapshotByInvoiceID(ctx, externalInvoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSnapshotByInvoiceID", reflect.TypeOf((*MockBillingRepository)(nil).FindSnapshotByInvoiceID), ctx, externalInvoiceID)
}

// MarkSnapshotFailedByInvoiceID mocks base method.
func (m *MockBillingRepository) MarkSnapshotFailedByInvoiceID(ctx context.Context, externalInvoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSnapshotFailedByInvoiceID", ctx, externalInvoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSnapshotFailedByInvoiceID indicates an expected call of MarkSnapshotFailedByInvoiceID.
func (mr *MockBillingRepositoryMockRecorder) MarkSnapshotFailedByInvoiceID(ctx, externalInvoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSnapshotFailedByInvoiceID", reflect.TypeOf((*MockBillingRepository)(nil).MarkSnapshotFailedByInvoiceID), ctx, externalInvoiceID)
}

// MarkSnapshotPaidByID mocks base method.
func (m *MockBillingRepository) MarkSnapshotPaidByID(ctx context.Context, snapshotID, externalInvoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSnapshotPaidByID", ctx, snapshotID, externalInvoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSnapshotPaidByID indicates an expected call of MarkSnapshotPaidByID.
func (mr *MockBillingRepositoryMockRecorder) MarkSnapshotPaidByID(ctx, snapshotID, externalInvoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSnapshotPaidByID", reflect.TypeOf((*MockBillingRepository)(nil).MarkSnapshotPaidByID), ctx, snapshotID, externalInvoiceID)
}

// MarkSnapshotPaidByInvoiceID mocks base method.
func (m *MockBillingRepository) MarkSnapshotPaidByInvoiceID(ctx context.Context, externalInvoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSnapshotPaidByInvoiceID", ctx, externalInvoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSnapshotPaidByInvoiceID indicates an expected call of MarkSnapshotPaidByInvoiceID.
func (mr *MockBillingRepositoryMockRecorder) MarkSnapshotPaidByInvoiceID(ctx, externalInvoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSnapshotPaidByInvoiceID", reflect.TypeOf((*MockBillingRepository)(nil).MarkSnapshotPaidByInvoiceID), ctx, externalInvoiceID)
}

// UpdateSnapshotInvoiceID mocks base method.
func (m *MockBillingRepository) UpdateSnapshotInvoiceID(ctx context.Context, snapshotID, invoiceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSnapshotInvoiceID", ctx, snapshotID, invoiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSnapshotInvoiceID indicates an expected call of UpdateSnapshotInvoiceID.
func (mr *MockBillingRepositoryMockRecorder) UpdateSnapshotInvoiceID(ctx, snapshotID, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSnapshotInvoiceID", reflect.TypeOf((*MockBillingRepository)(nil).UpdateSnapshotInvoiceID), ctx, snapshotID, invoiceID)
}

// UpdateSnapshotPaymentStatus mocks base method.
func (m *MockBillingRepository) UpdateSnapshotPaymentStatus(ctx context.Context, snapshotID string, status models0.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSnapshotPaymentStatus", ctx, snapshotID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSnapshotPaymentStatus indicates an expected call of UpdateSnapshotPaymentStatus.
func (mr *MockBillingRepositoryMockRecorder) UpdateSnapshotPaymentStatus(ctx, snapshotID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSnapshotPaymentStatus", reflect.TypeOf((*MockBillingRepository)(nil).UpdateSnapshotPaymentStatus), ctx, snapshotID, status)
}

// MockValkeyClient is a mock of ValkeyClient interface.
type MockValkeyClient struct {
	ctrl     *gomock.Controller
	recorder *MockValkeyClientMockRecorder
}

// MockValkeyClientMockRecorder is the mock recorder for MockValkeyClient.
type MockValkeyClientMockRecorder struct {
	mock *MockValkeyClient
}

// NewMockValkeyClient creates a new mock instance.
func NewMockValkeyClient(ctrl *gomock.Controller) *MockValkeyClient {
	mock := &MockValkeyClient{ctrl: ctrl}
	mock.recorder = &MockValkeyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValkeyClient) EXPECT() *MockValkeyClientMockRecorder {
	return m.recorder
}

// ApplyCreditTopupAtomic mocks base method.
func (m *MockValkeyClient) ApplyCreditTopupAtomic(ctx context.Context, balanceKey, pendingKey string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCreditTopupAtomic", ctx, balanceKey, pendingKey, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyCreditTopupAtomic indicates an expected call of ApplyCreditTopupAtomic.
func (mr *MockValkeyClientMockRecorder) ApplyCreditTopupAtomic(ctx, balanceKey, pendingKey, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCreditTopupAtomic", reflect.TypeOf((*MockValkeyClient)(nil).ApplyCreditTopupAtomic), ctx, balanceKey, pendingKey, amount)
}

// DecrBy mocks base method.
func (m *MockValkeyClient) DecrBy(ctx context.Context, key string, value int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrBy", ctx, key, value)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrBy indicates an expected call of DecrBy.
func (mr *MockValkeyClientMockRecorder) DecrBy(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrBy", reflect.TypeOf((*MockValkeyClient)(nil).DecrBy), ctx, key, value)
}

// Del mocks base method.
func (m *MockValkeyClient) Del(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockValkeyClientMockRecorder) Del(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockValkeyClient)(nil).Del), varargs...)
}

// Delete mocks base method.
func (m *MockValkeyClient) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockValkeyClientMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockValkeyClient)(nil).Delete), ctx, key)
}

// Eval mocks base method.
func (m *MockValkeyClient) Eval(ctx context.Context, script string, keys []string, args ...interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, script, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Eval", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Eval indicates an expected call of Eval.
func (mr *MockValkeyClientMockRecorder) Eval(ctx, script, keys interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, script, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eval", reflect.TypeOf((*MockValkeyClient)(nil).Eval), varargs...)
}

// EvalSHA mocks base method.
func (m *MockValkeyClient) EvalSHA(ctx context.Context, sha string, keys []string, args ...interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sha, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EvalSHA", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvalSHA indicates an expected call of EvalSHA.
func (mr *MockValkeyClientMockRecorder) EvalSHA(ctx, sha, keys interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sha, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalSHA", reflect.TypeOf((*MockValkeyClient)(nil).EvalSHA), varargs...)
}

// ExecuteWithBackoff mocks base method.
func (m *MockValkeyClient) ExecuteWithBackoff(ctx context.Context, operation func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithBackoff", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWithBackoff indicates an expected call of ExecuteWithBackoff.
func (mr *MockValkeyClientMockRecorder) ExecuteWithBackoff(ctx, operation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithBackoff", reflect.TypeOf((*MockValkeyClient)(nil).ExecuteWithBackoff), ctx, operation)
}

// Exists mocks base method.
func (m *MockValkeyClient) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockValkeyClientMockRecorder) Exists(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockValkeyClient)(nil).Exists), ctx, key)
}

// Expire mocks base method.
func (m *MockValkeyClient) Expire(ctx context.Context, key string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", ctx, key, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *MockValkeyClientMockRecorder) Expire(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockValkeyClient)(nil).Expire), ctx, key, ttl)
}

// Get mocks base method.
func (m *MockValkeyClient) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockValkeyClientMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockValkeyClient)(nil).Get), ctx, key)
}

// HDel mocks base method.
func (m *MockValkeyClient) HDel(ctx context.Context, key string, fields ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HDel", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HDel indicates an expected call of HDel.
func (mr *MockValkeyClientMockRecorder) HDel(ctx, key interface{}, fields ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HDel", reflect.TypeOf((*MockValkeyClient)(nil).HDel), varargs...)
}

// HGet mocks base method.
func (m *MockValkeyClient) HGet(ctx context.Context, key, field string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGet", ctx, key, field)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGet indicates an expected call of HGet.
func (mr *MockValkeyClientMockRecorder) HGet(ctx, key, field interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGet", reflect.TypeOf((*MockValkeyClient)(nil).HGet), ctx, key, field)
}

// HGetAll mocks base method.
func (m *MockValkeyClient) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HGetAll", ctx, key)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HGetAll indicates an expected call of HGetAll.
func (mr *MockValkeyClientMockRecorder) HGetAll(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HGetAll", reflect.TypeOf((*MockValkeyClient)(nil).HGetAll), ctx, key)
}

// HSet mocks base method.
func (m *MockValkeyClient) HSet(ctx context.Context, key string, values ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockValkeyClientMockRecorder) HSet(ctx, key interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockValkeyClient)(nil).HSet), varargs...)
}

// IncrBy mocks base method.
func (m *MockValkeyClient) IncrBy(ctx context.Context, key string, value int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrBy", ctx, key, value)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrBy indicates an expected call of IncrBy.
func (mr *MockValkeyClientMockRecorder) IncrBy(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrBy", reflect.TypeOf((*MockValkeyClient)(nil).IncrBy), ctx, key, value)
}

// Keys mocks base method.
func (m *MockValkeyClient) Keys(ctx context.Context, pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys", ctx, pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockValkeyClientMockRecorder) Keys(ctx, pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockValkeyClient)(nil).Keys), ctx, pattern)
}

// LPush mocks base method.
func (m *MockValkeyClient) LPush(ctx context.Context, key string, values ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LPush", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LPush indicates an expected call of LPush.
func (mr *MockValkeyClientMockRecorder) LPush(ctx, key interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockValkeyClient)(nil).LPush), varargs...)
}

// LRange mocks base method.
func (m *MockValkeyClient) LRange(ctx context.Context, key string, start, stop int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LRange", ctx, key, start, stop)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LRange indicates an expected call of LRange.
func (mr *MockValkeyClientMockRecorder) LRange(ctx, key, start, stop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LRange", reflect.TypeOf((*MockValkeyClient)(nil).LRange), ctx, key, start, stop)
}

// MGet mocks base method.
func (m *MockValkeyClient) MGet(ctx context.Context, keys ...string) (map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MGet", varargs...)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockValkeyClientMockRecorder) MGet(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockValkeyClient)(nil).MGet), varargs...)
}

// Pipeline mocks base method.
func (m *MockValkeyClient) Pipeline() interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pipeline")
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// Pipeline indicates an expected call of Pipeline.
func (mr *MockValkeyClientMockRecorder) Pipeline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pipeline", reflect.TypeOf((*MockValkeyClient)(nil).Pipeline))
}

// SAdd mocks base method.
func (m *MockValkeyClient) SAdd(ctx context.Context, key string, members ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SAdd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SAdd indicates an expected call of SAdd.
func (mr *MockValkeyClientMockRecorder) SAdd(ctx, key interface{}, members ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SAdd", reflect.TypeOf((*MockValkeyClient)(nil).SAdd), varargs...)
}

// SMembers mocks base method.
func (m *MockValkeyClient) SMembers(ctx context.Context, key string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SMembers", ctx, key)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SMembers indicates an expected call of SMembers.
func (mr *MockValkeyClientMockRecorder) SMembers(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SMembers", reflect.TypeOf((*MockValkeyClient)(nil).SMembers), ctx, key)
}

// SRem mocks base method.
func (m *MockValkeyClient) SRem(ctx context.Context, key string, members ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SRem", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SRem indicates an expected call of SRem.
func (mr *MockValkeyClientMockRecorder) SRem(ctx, key interface{}, members ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SRem", reflect.TypeOf((*MockValkeyClient)(nil).SRem), varargs...)
}

// ScriptLoad mocks base method.
func (m *MockValkeyClient) ScriptLoad(ctx context.Context, script string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScriptLoad", ctx, script)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScriptLoad indicates an expected call of ScriptLoad.
func (mr *MockValkeyClientMockRecorder) ScriptLoad(ctx, script interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScriptLoad", reflect.TypeOf((*MockValkeyClient)(nil).ScriptLoad), ctx, script)
}

// Set mocks base method.
func (m *MockValkeyClient) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockValkeyClientMockRecorder) Set(ctx, key, value, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockValkeyClient)(nil).Set), ctx, key, value, ttl)
}

// SetNX mocks base method.
func (m *MockValkeyClient) SetNX(ctx context.Context, key string, value interface{}, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockValkeyClientMockRecorder) SetNX(ctx, key, value, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockValkeyClient)(nil).SetNX), ctx, key, value, ttl)
}

// TTL mocks base method.
func (m *MockValkeyClient) TTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTL indicates an expected call of TTL.
func (mr *MockValkeyClientMockRecorder) TTL(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockValkeyClient)(nil).TTL), ctx, key)
}

// XAdd mocks base method.
func (m *MockValkeyClient) XAdd(ctx context.Context, stream, id string, values interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XAdd", ctx, stream, id, values)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XAdd indicates an expected call of XAdd.
func (mr *MockValkeyClientMockRecorder) XAdd(ctx, stream, id, values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAdd", reflect.TypeOf((*MockValkeyClient)(nil).XAdd), ctx, stream, id, values)
}

// ZAdd mocks base method.
func (m *MockValkeyClient) ZAdd(ctx context.Context, key string, score float64, member string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZAdd", ctx, key, score, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// ZAdd indicates an expected call of ZAdd.
func (mr *MockValkeyClientMockRecorder) ZAdd(ctx, key, score, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZAdd", reflect.TypeOf((*MockValkeyClient)(nil).ZAdd), ctx, key, score, member)
}

// ZCard mocks base method.
func (m *MockValkeyClient) ZCard(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZCard", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ZCard indicates an expected call of ZCard.
func (mr *MockValkeyClientMockRecorder) ZCard(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZCard", reflect.TypeOf((*MockValkeyClient)(nil).ZCard), ctx, key)
}

// ZRange mocks base method.
func (m *MockValkeyClient) ZRange(ctx context.Context, key string, start, stop int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ZRange", ctx, key, start, stop)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ZRange indicates an expected call of ZRange.
func (mr *MockValkeyClientMockRecorder) ZRange(ctx, key, start, stop interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZRange", reflect.TypeOf((*MockValkeyClient)(nil).ZRange), ctx, key, start, stop)
}

// ZRem mocks base method.
func (m *MockValkeyClient) ZRem(ctx context.Context, key string, members ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ZRem", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ZRem indicates an expected call of ZRem.
func (mr *MockValkeyClientMockRecorder) ZRem(ctx, key interface{}, members ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ZRem", reflect.TypeOf((*MockValkeyClient)(nil).ZRem), varargs...)
}

// MockValkeyPipeline is a mock of ValkeyPipeline interface.
type MockValkeyPipeline struct {
	ctrl     *gomock.Controller
	recorder *MockValkeyPipelineMockRecorder
}

// MockValkeyPipelineMockRecorder is the mock recorder for MockValkeyPipeline.
type MockValkeyPipelineMockRecorder struct {
	mock *MockValkeyPipeline
}

// NewMockValkeyPipeline creates a new mock instance.
func NewMockValkeyPipeline(ctrl *gomock.Controller) *MockValkeyPipeline {
	mock := &MockValkeyPipeline{ctrl: ctrl}
	mock.recorder = &MockValkeyPipelineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValkeyPipeline) EXPECT() *MockValkeyPipelineMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockValkeyPipeline) Del(ctx context.Context, keys ...string) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockValkeyPipelineMockRecorder) Del(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockValkeyPipeline)(nil).Del), varargs...)
}

// Exec mocks base method.
func (m *MockValkeyPipeline) Exec(ctx context.Context) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockValkeyPipelineMockRecorder) Exec(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockValkeyPipeline)(nil).Exec), ctx)
}

// Expire mocks base method.
func (m *MockValkeyPipeline) Expire(ctx context.Context, key string, expiration time.Duration) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", ctx, key, expiration)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *MockValkeyPipelineMockRecorder) Expire(ctx, key, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockValkeyPipeline)(nil).Expire), ctx, key, expiration)
}

// HDel mocks base method.
func (m *MockValkeyPipeline) HDel(ctx context.Context, key string, fields ...string) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HDel", varargs...)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// HDel indicates an expected call of HDel.
func (mr *MockValkeyPipelineMockRecorder) HDel(ctx, key interface{}, fields ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HDel", reflect.TypeOf((*MockValkeyPipeline)(nil).HDel), varargs...)
}

// HSet mocks base method.
func (m *MockValkeyPipeline) HSet(ctx context.Context, key string, values ...interface{}) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HSet", varargs...)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// HSet indicates an expected call of HSet.
func (mr *MockValkeyPipelineMockRecorder) HSet(ctx, key interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HSet", reflect.TypeOf((*MockValkeyPipeline)(nil).HSet), varargs...)
}

// LPush mocks base method.
func (m *MockValkeyPipeline) LPush(ctx context.Context, key string, values ...interface{}) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LPush", varargs...)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// LPush indicates an expected call of LPush.
func (mr *MockValkeyPipelineMockRecorder) LPush(ctx, key interface{}, values ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LPush", reflect.TypeOf((*MockValkeyPipeline)(nil).LPush), varargs...)
}

// Set mocks base method.
func (m *MockValkeyPipeline) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) interfaces.ValkeyPipeline {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(interfaces.ValkeyPipeline)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockValkeyPipelineMockRecorder) Set(ctx, key, value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockValkeyPipeline)(nil).Set), ctx, key, value, expiration)
}

// MockThreadRepository is a mock of ThreadRepository interface.
type MockThreadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThreadRepositoryMockRecorder
}

// MockThreadRepositoryMockRecorder is the mock recorder for MockThreadRepository.
type MockThreadRepositoryMockRecorder struct {
	mock *MockThreadRepository
}

// NewMockThreadRepository creates a new mock instance.
func NewMockThreadRepository(ctrl *gomock.Controller) *MockThreadRepository {
	mock := &MockThreadRepository{ctrl: ctrl}
	mock.recorder = &MockThreadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadRepository) EXPECT() *MockThreadRepositoryMockRecorder {
	return m.recorder
}

// AddRefs mocks base method.
func (m *MockThreadRepository) AddRefs(ctx context.Context, threadID string, refs map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRefs", ctx, threadID, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRefs indicates an expected call of AddRefs.
func (mr *MockThreadRepositoryMockRecorder) AddRefs(ctx, threadID, refs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefs", reflect.TypeOf((*MockThreadRepository)(nil).AddRefs), ctx, threadID, refs)
}

// Delete mocks base method.
func (m *MockThreadRepository) Delete(ctx context.Context, threadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, threadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockThreadRepositoryMockRecorder) Delete(ctx, threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockThreadRepository)(nil).Delete), ctx, threadID)
}

// Exists mocks base method.
func (m *MockThreadRepository) Exists(ctx context.Context, threadID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, threadID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockThreadRepositoryMockRecorder) Exists(ctx, threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockThreadRepository)(nil).Exists), ctx, threadID)
}

// ExtendTTL mocks base method.
func (m *MockThreadRepository) ExtendTTL(ctx context.Context, threadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendTTL", ctx, threadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendTTL indicates an expected call of ExtendTTL.
func (mr *MockThreadRepositoryMockRecorder) ExtendTTL(ctx, threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendTTL", reflect.TypeOf((*MockThreadRepository)(nil).ExtendTTL), ctx, threadID)
}

// Get mocks base method.
func (m *MockThreadRepository) Get(ctx context.Context, threadID string, writeBack ...bool) (*models.Thread, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*models.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockThreadRepositoryMockRecorder) Get(ctx, threadID interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThreadRepository)(nil).Get), varargs...)
}

// GetByOwner mocks base method.
func (m *MockThreadRepository) GetByOwner(ctx context.Context, ownerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwner", ctx, ownerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwner indicates an expected call of GetByOwner.
func (mr *MockThreadRepositoryMockRecorder) GetByOwner(ctx, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwner", reflect.TypeOf((*MockThreadRepository)(nil).GetByOwner), ctx, ownerID)
}

// GetCompletedSteps mocks base method.
func (m *MockThreadRepository) GetCompletedSteps(ctx context.Context, threadID string, writeBack ...bool) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCompletedSteps", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedSteps indicates an expected call of GetCompletedSteps.
func (mr *MockThreadRepositoryMockRecorder) GetCompletedSteps(ctx, threadID interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedSteps", reflect.TypeOf((*MockThreadRepository)(nil).GetCompletedSteps), varargs...)
}

// GetCompletedStepsCount mocks base method.
func (m *MockThreadRepository) GetCompletedStepsCount(ctx context.Context, threadID string, writeBack ...bool) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCompletedStepsCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompletedStepsCount indicates an expected call of GetCompletedStepsCount.
func (mr *MockThreadRepositoryMockRecorder) GetCompletedStepsCount(ctx, threadID interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompletedStepsCount", reflect.TypeOf((*MockThreadRepository)(nil).GetCompletedStepsCount), varargs...)
}

// GetStepStatus mocks base method.
func (m *MockThreadRepository) GetStepStatus(ctx context.Context, threadID, stepName, stepStatus, idempotencyKey string, writeBack ...bool) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID, stepName, stepStatus, idempotencyKey}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStepStatus", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStepStatus indicates an expected call of GetStepStatus.
func (mr *MockThreadRepositoryMockRecorder) GetStepStatus(ctx, threadID, stepName, stepStatus, idempotencyKey interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID, stepName, stepStatus, idempotencyKey}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepStatus", reflect.TypeOf((*MockThreadRepository)(nil).GetStepStatus), varargs...)
}

// Save mocks base method.
func (m *MockThreadRepository) Save(ctx context.Context, thread *models.Thread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockThreadRepositoryMockRecorder) Save(ctx, thread interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockThreadRepository)(nil).Save), ctx, thread)
}

// UpdateThreadStatus mocks base method.
func (m *MockThreadRepository) UpdateThreadStatus(ctx context.Context, threadID, status string, timestamp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThreadStatus", ctx, threadID, status, timestamp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThreadStatus indicates an expected call of UpdateThreadStatus.
func (mr *MockThreadRepositoryMockRecorder) UpdateThreadStatus(ctx, threadID, status, timestamp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThreadStatus", reflect.TypeOf((*MockThreadRepository)(nil).UpdateThreadStatus), ctx, threadID, status, timestamp)
}

// MockAccessRepository is a mock of AccessRepository interface.
type MockAccessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessRepositoryMockRecorder
}

// MockAccessRepositoryMockRecorder is the mock recorder for MockAccessRepository.
type MockAccessRepositoryMockRecorder struct {
	mock *MockAccessRepository
}

// NewMockAccessRepository creates a new mock instance.
func NewMockAccessRepository(ctrl *gomock.Controller) *MockAccessRepository {
	mock := &MockAccessRepository{ctrl: ctrl}
	mock.recorder = &MockAccessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessRepository) EXPECT() *MockAccessRepositoryMockRecorder {
	return m.recorder
}

// GetAllAccess mocks base method.
func (m *MockAccessRepository) GetAllAccess(ctx context.Context, threadID string, writeBack ...bool) (map[string]*interfaces.UserAccess, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllAccess", varargs...)
	ret0, _ := ret[0].(map[string]*interfaces.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccess indicates an expected call of GetAllAccess.
func (mr *MockAccessRepositoryMockRecorder) GetAllAccess(ctx, threadID interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccess", reflect.TypeOf((*MockAccessRepository)(nil).GetAllAccess), varargs...)
}

// GetUserAccess mocks base method.
func (m *MockAccessRepository) GetUserAccess(ctx context.Context, threadID, userID string, writeBack ...bool) (*interfaces.UserAccess, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, threadID, userID}
	for _, a := range writeBack {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserAccess", varargs...)
	ret0, _ := ret[0].(*interfaces.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccess indicates an expected call of GetUserAccess.
func (mr *MockAccessRepositoryMockRecorder) GetUserAccess(ctx, threadID, userID interface{}, writeBack ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, threadID, userID}, writeBack...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccess", reflect.TypeOf((*MockAccessRepository)(nil).GetUserAccess), varargs...)
}

// GrantOrUpdateAccess mocks base method.
func (m *MockAccessRepository) GrantOrUpdateAccess(ctx context.Context, threadID, userID, role, runtimeRole string, permissions []string, invitedBy string, luaScripts interfaces.LuaScriptManager, threadData *string, threadTTL *int) (*interfaces.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantOrUpdateAccess", ctx, threadID, userID, role, runtimeRole, permissions, invitedBy, luaScripts, threadData, threadTTL)
	ret0, _ := ret[0].(*interfaces.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantOrUpdateAccess indicates an expected call of GrantOrUpdateAccess.
func (mr *MockAccessRepositoryMockRecorder) GrantOrUpdateAccess(ctx, threadID, userID, role, runtimeRole, permissions, invitedBy, luaScripts, threadData, threadTTL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantOrUpdateAccess", reflect.TypeOf((*MockAccessRepository)(nil).GrantOrUpdateAccess), ctx, threadID, userID, role, runtimeRole, permissions, invitedBy, luaScripts, threadData, threadTTL)
}

// RevokeAccess mocks base method.
func (m *MockAccessRepository) RevokeAccess(ctx context.Context, threadID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccess", ctx, threadID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAccess indicates an expected call of RevokeAccess.
func (mr *MockAccessRepositoryMockRecorder) RevokeAccess(ctx, threadID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockAccessRepository)(nil).RevokeAccess), ctx, threadID, userID)
}

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// ArchiveStepState mocks base method.
func (m *MockActivityRepository) ArchiveStepState(ctx context.Context, stepState *interfaces.StepStateSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveStepState", ctx, stepState)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveStepState indicates an expected call of ArchiveStepState.
func (mr *MockActivityRepositoryMockRecorder) ArchiveStepState(ctx, stepState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveStepState", reflect.TypeOf((*MockActivityRepository)(nil).ArchiveStepState), ctx, stepState)
}

// ArchiveThreadMetadata mocks base method.
func (m *MockActivityRepository) ArchiveThreadMetadata(ctx context.Context, thread *models.Thread, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveThreadMetadata", ctx, thread, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveThreadMetadata indicates an expected call of ArchiveThreadMetadata.
func (mr *MockActivityRepositoryMockRecorder) ArchiveThreadMetadata(ctx, thread, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveThreadMetadata", reflect.TypeOf((*MockActivityRepository)(nil).ArchiveThreadMetadata), ctx, thread, status)
}

// ArchiveValidationResults mocks base method.
func (m *MockActivityRepository) ArchiveValidationResults(ctx context.Context, threadID, stepID, stepName, idempotencyKey string, notifications []models.ValidationNotification, finalStatus string, hasCriticalViolation bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveValidationResults", ctx, threadID, stepID, stepName, idempotencyKey, notifications, finalStatus, hasCriticalViolation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveValidationResults indicates an expected call of ArchiveValidationResults.
func (mr *MockActivityRepositoryMockRecorder) ArchiveValidationResults(ctx, threadID, stepID, stepName, idempotencyKey, notifications, finalStatus, hasCriticalViolation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveValidationResults", reflect.TypeOf((*MockActivityRepository)(nil).ArchiveValidationResults), ctx, threadID, stepID, stepName, idempotencyKey, notifications, finalStatus, hasCriticalViolation)
}

// GetActivityLog mocks base method.
func (m *MockActivityRepository) GetActivityLog(ctx context.Context, threadID string) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityLog", ctx, threadID)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityLog indicates an expected call of GetActivityLog.
func (mr *MockActivityRepositoryMockRecorder) GetActivityLog(ctx, threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityLog", reflect.TypeOf((*MockActivityRepository)(nil).GetActivityLog), ctx, threadID)
}

// RecordAccessGranted mocks base method.
func (m *MockActivityRepository) RecordAccessGranted(ctx context.Context, threadID, userID string, access *interfaces.UserAccess, invitedBy, serviceName, runtimeRole string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAccessGranted", ctx, threadID, userID, access, invitedBy, serviceName, runtimeRole)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAccessGranted indicates an expected call of RecordAccessGranted.
func (mr *MockActivityRepositoryMockRecorder) RecordAccessGranted(ctx, threadID, userID, access, invitedBy, serviceName, runtimeRole interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAccessGranted", reflect.TypeOf((*MockActivityRepository)(nil).RecordAccessGranted), ctx, threadID, userID, access, invitedBy, serviceName, runtimeRole)
}

// RecordInvitationUsed mocks base method.
func (m *MockActivityRepository) RecordInvitationUsed(ctx context.Context, threadID, userID, role, invitedBy, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordInvitationUsed", ctx, threadID, userID, role, invitedBy, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordInvitationUsed indicates an expected call of RecordInvitationUsed.
func (mr *MockActivityRepositoryMockRecorder) RecordInvitationUsed(ctx, threadID, userID, role, invitedBy, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordInvitationUsed", reflect.TypeOf((*MockActivityRepository)(nil).RecordInvitationUsed), ctx, threadID, userID, role, invitedBy, serviceName)
}

// RecordThreadCreated mocks base method.
func (m *MockActivityRepository) RecordThreadCreated(ctx context.Context, threadID, creatorID, creatorRole, serviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordThreadCreated", ctx, threadID, creatorID, creatorRole, serviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordThreadCreated indicates an expected call of RecordThreadCreated.
func (mr *MockActivityRepositoryMockRecorder) RecordThreadCreated(ctx, threadID, creatorID, creatorRole, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordThreadCreated", reflect.TypeOf((*MockActivityRepository)(nil).RecordThreadCreated), ctx, threadID, creatorID, creatorRole, serviceName)
}

// MockContractGraphRepository is a mock of ContractGraphRepository interface.
type MockContractGraphRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContractGraphRepositoryMockRecorder
}

// MockContractGraphRepositoryMockRecorder is the mock recorder for MockContractGraphRepository.
type MockContractGraphRepositoryMockRecorder struct {
	mock *MockContractGraphRepository
}

// NewMockContractGraphRepository creates a new mock instance.
func NewMockContractGraphRepository(ctrl *gomock.Controller) *MockContractGraphRepository {
	mock := &MockContractGraphRepository{ctrl: ctrl}
	mock.recorder = &MockContractGraphRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractGraphRepository) EXPECT() *MockContractGraphRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockContractGraphRepository) Delete(ctx context.Context, contractName string, version int, companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contractName, version, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContractGraphRepositoryMockRecorder) Delete(ctx, contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContractGraphRepository)(nil).Delete), ctx, contractName, version, companyID)
}

// Exists mocks base method.
func (m *MockContractGraphRepository) Exists(ctx context.Context, contractName string, version int, companyID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, contractName, version, companyID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockContractGraphRepositoryMockRecorder) Exists(ctx, contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockContractGraphRepository)(nil).Exists), ctx, contractName, version, companyID)
}

// Get mocks base method.
func (m *MockContractGraphRepository) Get(ctx context.Context, contractName string, version int, companyID string) (*models.ContractGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, contractName, version, companyID)
	ret0, _ := ret[0].(*models.ContractGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContractGraphRepositoryMockRecorder) Get(ctx, contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContractGraphRepository)(nil).Get), ctx, contractName, version, companyID)
}

// Save mocks base method.
func (m *MockContractGraphRepository) Save(ctx context.Context, contractName string, version int, companyID string, graph *models.ContractGraph) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, contractName, version, companyID, graph)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockContractGraphRepositoryMockRecorder) Save(ctx, contractName, version, companyID, graph interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockContractGraphRepository)(nil).Save), ctx, contractName, version, companyID, graph)
}

// MockLuaScriptManager is a mock of LuaScriptManager interface.
type MockLuaScriptManager struct {
	ctrl     *gomock.Controller
	recorder *MockLuaScriptManagerMockRecorder
}

// MockLuaScriptManagerMockRecorder is the mock recorder for MockLuaScriptManager.
type MockLuaScriptManagerMockRecorder struct {
	mock *MockLuaScriptManager
}

// NewMockLuaScriptManager creates a new mock instance.
func NewMockLuaScriptManager(ctrl *gomock.Controller) *MockLuaScriptManager {
	mock := &MockLuaScriptManager{ctrl: ctrl}
	mock.recorder = &MockLuaScriptManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLuaScriptManager) EXPECT() *MockLuaScriptManagerMockRecorder {
	return m.recorder
}

// CheckCompanyRateLimit mocks base method.
func (m *MockLuaScriptManager) CheckCompanyRateLimit(ctx context.Context, companyID string, requestsPerMinute, windowSeconds int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCompanyRateLimit", ctx, companyID, requestsPerMinute, windowSeconds)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCompanyRateLimit indicates an expected call of CheckCompanyRateLimit.
func (mr *MockLuaScriptManagerMockRecorder) CheckCompanyRateLimit(ctx, companyID, requestsPerMinute, windowSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCompanyRateLimit", reflect.TypeOf((*MockLuaScriptManager)(nil).CheckCompanyRateLimit), ctx, companyID, requestsPerMinute, windowSeconds)
}

// CheckIPRateLimit mocks base method.
func (m *MockLuaScriptManager) CheckIPRateLimit(ctx context.Context, ip string, requestsPerWindow, windowSeconds int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIPRateLimit", ctx, ip, requestsPerWindow, windowSeconds)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIPRateLimit indicates an expected call of CheckIPRateLimit.
func (mr *MockLuaScriptManagerMockRecorder) CheckIPRateLimit(ctx, ip, requestsPerWindow, windowSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIPRateLimit", reflect.TypeOf((*MockLuaScriptManager)(nil).CheckIPRateLimit), ctx, ip, requestsPerWindow, windowSeconds)
}

// DecrementCreditWithAutoTopup mocks base method.
func (m *MockLuaScriptManager) DecrementCreditWithAutoTopup(ctx context.Context, params *interfaces.DebitParams) (interfaces.DebitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementCreditWithAutoTopup", ctx, params)
	ret0, _ := ret[0].(interfaces.DebitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementCreditWithAutoTopup indicates an expected call of DecrementCreditWithAutoTopup.
func (mr *MockLuaScriptManagerMockRecorder) DecrementCreditWithAutoTopup(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementCreditWithAutoTopup", reflect.TypeOf((*MockLuaScriptManager)(nil).DecrementCreditWithAutoTopup), ctx, params)
}

// GetAndResetCharged mocks base method.
func (m *MockLuaScriptManager) GetAndResetCharged(ctx context.Context, balanceKey, chargedKey string) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndResetCharged", ctx, balanceKey, chargedKey)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAndResetCharged indicates an expected call of GetAndResetCharged.
func (mr *MockLuaScriptManagerMockRecorder) GetAndResetCharged(ctx, balanceKey, chargedKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndResetCharged", reflect.TypeOf((*MockLuaScriptManager)(nil).GetAndResetCharged), ctx, balanceKey, chargedKey)
}

// GetScriptHash mocks base method.
func (m *MockLuaScriptManager) GetScriptHash(name string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScriptHash", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetScriptHash indicates an expected call of GetScriptHash.
func (mr *MockLuaScriptManagerMockRecorder) GetScriptHash(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScriptHash", reflect.TypeOf((*MockLuaScriptManager)(nil).GetScriptHash), name)
}

// MockNATSClient is a mock of NATSClient interface.
type MockNATSClient struct {
	ctrl     *gomock.Controller
	recorder *MockNATSClientMockRecorder
}

// MockNATSClientMockRecorder is the mock recorder for MockNATSClient.
type MockNATSClientMockRecorder struct {
	mock *MockNATSClient
}

// NewMockNATSClient creates a new mock instance.
func NewMockNATSClient(ctrl *gomock.Controller) *MockNATSClient {
	mock := &MockNATSClient{ctrl: ctrl}
	mock.recorder = &MockNATSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSClient) EXPECT() *MockNATSClientMockRecorder {
	return m.recorder
}

// FetchMessage mocks base method.
func (m *MockNATSClient) FetchMessage(subject, consumerName string, timeout time.Duration) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMessage", subject, consumerName, timeout)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMessage indicates an expected call of FetchMessage.
func (mr *MockNATSClientMockRecorder) FetchMessage(subject, consumerName, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMessage", reflect.TypeOf((*MockNATSClient)(nil).FetchMessage), subject, consumerName, timeout)
}
