// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	interfaces "github.com/threadify/engine/internal/interfaces"
	models "github.com/threadify/engine/internal/models"
	validator "github.com/threadify/engine/pkg/validator"
)

// MockStepEventProcessor is a mock of StepEventProcessor interface.
type MockStepEventProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockStepEventProcessorMockRecorder
}

// MockStepEventProcessorMockRecorder is the mock recorder for MockStepEventProcessor.
type MockStepEventProcessorMockRecorder struct {
	mock *MockStepEventProcessor
}

// NewMockStepEventProcessor creates a new mock instance.
func NewMockStepEventProcessor(ctrl *gomock.Controller) *MockStepEventProcessor {
	mock := &MockStepEventProcessor{ctrl: ctrl}
	mock.recorder = &MockStepEventProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepEventProcessor) EXPECT() *MockStepEventProcessorMockRecorder {
	return m.recorder
}

// RecordStepEventDirect mocks base method.
func (m *MockStepEventProcessor) RecordStepEventDirect(ctx context.Context, event models.StepEvent, ownerID, serviceName string, subSteps []models.SubStepRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordStepEventDirect", ctx, event, ownerID, serviceName, subSteps)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordStepEventDirect indicates an expected call of RecordStepEventDirect.
func (mr *MockStepEventProcessorMockRecorder) RecordStepEventDirect(ctx, event, ownerID, serviceName, subSteps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordStepEventDirect", reflect.TypeOf((*MockStepEventProcessor)(nil).RecordStepEventDirect), ctx, event, ownerID, serviceName, subSteps)
}

// Start mocks base method.
func (m *MockStepEventProcessor) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStepEventProcessorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStepEventProcessor)(nil).Start))
}

// Stop mocks base method.
func (m *MockStepEventProcessor) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockStepEventProcessorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStepEventProcessor)(nil).Stop))
}

// MockConnectionManager is a mock of ConnectionManager interface.
type MockConnectionManager struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionManagerMockRecorder
}

// MockConnectionManagerMockRecorder is the mock recorder for MockConnectionManager.
type MockConnectionManagerMockRecorder struct {
	mock *MockConnectionManager
}

// NewMockConnectionManager creates a new mock instance.
func NewMockConnectionManager(ctrl *gomock.Controller) *MockConnectionManager {
	mock := &MockConnectionManager{ctrl: ctrl}
	mock.recorder = &MockConnectionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionManager) EXPECT() *MockConnectionManagerMockRecorder {
	return m.recorder
}

// ConnectWithOwnerAndCompany mocks base method.
func (m *MockConnectionManager) ConnectWithOwnerAndCompany(ownerID, apiKey, serviceName, companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectWithOwnerAndCompany", ownerID, apiKey, serviceName, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectWithOwnerAndCompany indicates an expected call of ConnectWithOwnerAndCompany.
func (mr *MockConnectionManagerMockRecorder) ConnectWithOwnerAndCompany(ownerID, apiKey, serviceName, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectWithOwnerAndCompany", reflect.TypeOf((*MockConnectionManager)(nil).ConnectWithOwnerAndCompany), ownerID, apiKey, serviceName, companyID)
}

// Disconnect mocks base method.
func (m *MockConnectionManager) Disconnect(ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect", ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockConnectionManagerMockRecorder) Disconnect(ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockConnectionManager)(nil).Disconnect), ownerID)
}

// GetClient mocks base method.
func (m *MockConnectionManager) GetClient(ownerID string) (*models.ConnectedClient, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ownerID)
	ret0, _ := ret[0].(*models.ConnectedClient)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockConnectionManagerMockRecorder) GetClient(ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockConnectionManager)(nil).GetClient), ownerID)
}

// GetClientCompany mocks base method.
func (m *MockConnectionManager) GetClientCompany(ownerID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientCompany", ownerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClientCompany indicates an expected call of GetClientCompany.
func (mr *MockConnectionManagerMockRecorder) GetClientCompany(ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientCompany", reflect.TypeOf((*MockConnectionManager)(nil).GetClientCompany), ownerID)
}

// IsConnected mocks base method.
func (m *MockConnectionManager) IsConnected(ownerID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected", ownerID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockConnectionManagerMockRecorder) IsConnected(ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockConnectionManager)(nil).IsConnected), ownerID)
}

// MockCacheManager is a mock of CacheManager interface.
type MockCacheManager struct {
	ctrl     *gomock.Controller
	recorder *MockCacheManagerMockRecorder
}

// MockCacheManagerMockRecorder is the mock recorder for MockCacheManager.
type MockCacheManagerMockRecorder struct {
	mock *MockCacheManager
}

// NewMockCacheManager creates a new mock instance.
func NewMockCacheManager(ctrl *gomock.Controller) *MockCacheManager {
	mock := &MockCacheManager{ctrl: ctrl}
	mock.recorder = &MockCacheManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheManager) EXPECT() *MockCacheManagerMockRecorder {
	return m.recorder
}

// ClearContractCache mocks base method.
func (m *MockCacheManager) ClearContractCache(contractName string, version int, companyID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearContractCache", contractName, version, companyID)
}

// ClearContractCache indicates an expected call of ClearContractCache.
func (mr *MockCacheManagerMockRecorder) ClearContractCache(contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearContractCache", reflect.TypeOf((*MockCacheManager)(nil).ClearContractCache), contractName, version, companyID)
}

// ClearStepStatus mocks base method.
func (m *MockCacheManager) ClearStepStatus(stepHashKey string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearStepStatus", stepHashKey)
}

// ClearStepStatus indicates an expected call of ClearStepStatus.
func (mr *MockCacheManagerMockRecorder) ClearStepStatus(stepHashKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearStepStatus", reflect.TypeOf((*MockCacheManager)(nil).ClearStepStatus), stepHashKey)
}

// ClearThreadCache mocks base method.
func (m *MockCacheManager) ClearThreadCache(threadID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearThreadCache", threadID)
}

// ClearThreadCache indicates an expected call of ClearThreadCache.
func (mr *MockCacheManagerMockRecorder) ClearThreadCache(threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearThreadCache", reflect.TypeOf((*MockCacheManager)(nil).ClearThreadCache), threadID)
}

// ClearThreadRoles mocks base method.
func (m *MockCacheManager) ClearThreadRoles(threadID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearThreadRoles", threadID)
}

// ClearThreadRoles indicates an expected call of ClearThreadRoles.
func (mr *MockCacheManagerMockRecorder) ClearThreadRoles(threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearThreadRoles", reflect.TypeOf((*MockCacheManager)(nil).ClearThreadRoles), threadID)
}

// GetContractGraph mocks base method.
func (m *MockCacheManager) GetContractGraph(contractName string, version int, companyID string) (*models.ContractGraph, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractGraph", contractName, version, companyID)
	ret0, _ := ret[0].(*models.ContractGraph)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetContractGraph indicates an expected call of GetContractGraph.
func (mr *MockCacheManagerMockRecorder) GetContractGraph(contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractGraph", reflect.TypeOf((*MockCacheManager)(nil).GetContractGraph), contractName, version, companyID)
}

// GetRuntimeRolePermissions mocks base method.
func (m *MockCacheManager) GetRuntimeRolePermissions(runtimeRole string) ([]string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeRolePermissions", runtimeRole)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetRuntimeRolePermissions indicates an expected call of GetRuntimeRolePermissions.
func (mr *MockCacheManagerMockRecorder) GetRuntimeRolePermissions(runtimeRole interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeRolePermissions", reflect.TypeOf((*MockCacheManager)(nil).GetRuntimeRolePermissions), runtimeRole)
}

// GetStepStatus mocks base method.
func (m *MockCacheManager) GetStepStatus(stepHashKey string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStepStatus", stepHashKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetStepStatus indicates an expected call of GetStepStatus.
func (mr *MockCacheManagerMockRecorder) GetStepStatus(stepHashKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepStatus", reflect.TypeOf((*MockCacheManager)(nil).GetStepStatus), stepHashKey)
}

// GetThread mocks base method.
func (m *MockCacheManager) GetThread(threadID string) (*models.Thread, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThread", threadID)
	ret0, _ := ret[0].(*models.Thread)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetThread indicates an expected call of GetThread.
func (mr *MockCacheManagerMockRecorder) GetThread(threadID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThread", reflect.TypeOf((*MockCacheManager)(nil).GetThread), threadID)
}

// GetUserRole mocks base method.
func (m *MockCacheManager) GetUserRole(threadID, userID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", threadID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockCacheManagerMockRecorder) GetUserRole(threadID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockCacheManager)(nil).GetUserRole), threadID, userID)
}

// SetContractGraph mocks base method.
func (m *MockCacheManager) SetContractGraph(contractName string, version int, companyID string, graph *models.ContractGraph) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContractGraph", contractName, version, companyID, graph)
}

// SetContractGraph indicates an expected call of SetContractGraph.
func (mr *MockCacheManagerMockRecorder) SetContractGraph(contractName, version, companyID, graph interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContractGraph", reflect.TypeOf((*MockCacheManager)(nil).SetContractGraph), contractName, version, companyID, graph)
}

// SetRuntimeRolePermissions mocks base method.
func (m *MockCacheManager) SetRuntimeRolePermissions(runtimeRole string, permissions []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRuntimeRolePermissions", runtimeRole, permissions)
}

// SetRuntimeRolePermissions indicates an expected call of SetRuntimeRolePermissions.
func (mr *MockCacheManagerMockRecorder) SetRuntimeRolePermissions(runtimeRole, permissions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRuntimeRolePermissions", reflect.TypeOf((*MockCacheManager)(nil).SetRuntimeRolePermissions), runtimeRole, permissions)
}

// SetStepStatus mocks base method.
func (m *MockCacheManager) SetStepStatus(stepHashKey, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStepStatus", stepHashKey, status)
}

// SetStepStatus indicates an expected call of SetStepStatus.
func (mr *MockCacheManagerMockRecorder) SetStepStatus(stepHashKey, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStepStatus", reflect.TypeOf((*MockCacheManager)(nil).SetStepStatus), stepHashKey, status)
}

// SetThread mocks base method.
func (m *MockCacheManager) SetThread(threadID string, thread *models.Thread) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetThread", threadID, thread)
}

// SetThread indicates an expected call of SetThread.
func (mr *MockCacheManagerMockRecorder) SetThread(threadID, thread interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetThread", reflect.TypeOf((*MockCacheManager)(nil).SetThread), threadID, thread)
}

// SetUserRole mocks base method.
func (m *MockCacheManager) SetUserRole(threadID, userID, role string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserRole", threadID, userID, role)
}

// SetUserRole indicates an expected call of SetUserRole.
func (mr *MockCacheManagerMockRecorder) SetUserRole(threadID, userID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserRole", reflect.TypeOf((*MockCacheManager)(nil).SetUserRole), threadID, userID, role)
}

// MockContractGraphValidator is a mock of ContractGraphValidator interface.
type MockContractGraphValidator struct {
	ctrl     *gomock.Controller
	recorder *MockContractGraphValidatorMockRecorder
}

// MockContractGraphValidatorMockRecorder is the mock recorder for MockContractGraphValidator.
type MockContractGraphValidatorMockRecorder struct {
	mock *MockContractGraphValidator
}

// NewMockContractGraphValidator creates a new mock instance.
func NewMockContractGraphValidator(ctrl *gomock.Controller) *MockContractGraphValidator {
	mock := &MockContractGraphValidator{ctrl: ctrl}
	mock.recorder = &MockContractGraphValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractGraphValidator) EXPECT() *MockContractGraphValidatorMockRecorder {
	return m.recorder
}

// GetContractByNameAndCompany mocks base method.
func (m *MockContractGraphValidator) GetContractByNameAndCompany(contractName, companyID string) (*models.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractByNameAndCompany", contractName, companyID)
	ret0, _ := ret[0].(*models.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractByNameAndCompany indicates an expected call of GetContractByNameAndCompany.
func (mr *MockContractGraphValidatorMockRecorder) GetContractByNameAndCompany(contractName, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractByNameAndCompany", reflect.TypeOf((*MockContractGraphValidator)(nil).GetContractByNameAndCompany), contractName, companyID)
}

// GetContractGraph mocks base method.
func (m *MockContractGraphValidator) GetContractGraph(contractName string, version int, companyID string) (*models.ContractGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractGraph", contractName, version, companyID)
	ret0, _ := ret[0].(*models.ContractGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContractGraph indicates an expected call of GetContractGraph.
func (mr *MockContractGraphValidatorMockRecorder) GetContractGraph(contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractGraph", reflect.TypeOf((*MockContractGraphValidator)(nil).GetContractGraph), contractName, version, companyID)
}

// LoadContractGraphIntoCache mocks base method.
func (m *MockContractGraphValidator) LoadContractGraphIntoCache(contractName string, version int, companyID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadContractGraphIntoCache", contractName, version, companyID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadContractGraphIntoCache indicates an expected call of LoadContractGraphIntoCache.
func (mr *MockContractGraphValidatorMockRecorder) LoadContractGraphIntoCache(contractName, version, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadContractGraphIntoCache", reflect.TypeOf((*MockContractGraphValidator)(nil).LoadContractGraphIntoCache), contractName, version, companyID)
}

// ValidateStepContext mocks base method.
func (m *MockContractGraphValidator) ValidateStepContext(stepNode models.GraphNode, context map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStepContext", stepNode, context)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStepContext indicates an expected call of ValidateStepContext.
func (mr *MockContractGraphValidatorMockRecorder) ValidateStepContext(stepNode, context interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStepContext", reflect.TypeOf((*MockContractGraphValidator)(nil).ValidateStepContext), stepNode, context)
}

// ValidateStepInContract mocks base method.
func (m *MockContractGraphValidator) ValidateStepInContract(contractName string, version int, stepName string, context map[string]string, companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStepInContract", contractName, version, stepName, context, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStepInContract indicates an expected call of ValidateStepInContract.
func (mr *MockContractGraphValidatorMockRecorder) ValidateStepInContract(contractName, version, stepName, context, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStepInContract", reflect.TypeOf((*MockContractGraphValidator)(nil).ValidateStepInContract), contractName, version, stepName, context, companyID)
}

// MockBackgroundService is a mock of BackgroundService interface.
type MockBackgroundService struct {
	ctrl     *gomock.Controller
	recorder *MockBackgroundServiceMockRecorder
}

// MockBackgroundServiceMockRecorder is the mock recorder for MockBackgroundService.
type MockBackgroundServiceMockRecorder struct {
	mock *MockBackgroundService
}

// NewMockBackgroundService creates a new mock instance.
func NewMockBackgroundService(ctrl *gomock.Controller) *MockBackgroundService {
	mock := &MockBackgroundService{ctrl: ctrl}
	mock.recorder = &MockBackgroundServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackgroundService) EXPECT() *MockBackgroundServiceMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockBackgroundService) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockBackgroundServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockBackgroundService)(nil).Start))
}

// Stop mocks base method.
func (m *MockBackgroundService) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockBackgroundServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBackgroundService)(nil).Stop))
}

// MockContractValidator is a mock of ContractValidator interface.
type MockContractValidator struct {
	ctrl     *gomock.Controller
	recorder *MockContractValidatorMockRecorder
}

// MockContractValidatorMockRecorder is the mock recorder for MockContractValidator.
type MockContractValidatorMockRecorder struct {
	mock *MockContractValidator
}

// NewMockContractValidator creates a new mock instance.
func NewMockContractValidator(ctrl *gomock.Controller) *MockContractValidator {
	mock := &MockContractValidator{ctrl: ctrl}
	mock.recorder = &MockContractValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractValidator) EXPECT() *MockContractValidatorMockRecorder {
	return m.recorder
}

// SerializeContract mocks base method.
func (m *MockContractValidator) SerializeContract(contract *validator.Contract) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeContract", contract)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SerializeContract indicates an expected call of SerializeContract.
func (mr *MockContractValidatorMockRecorder) SerializeContract(contract interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeContract", reflect.TypeOf((*MockContractValidator)(nil).SerializeContract), contract)
}

// Validate mocks base method.
func (m *MockContractValidator) Validate(yamlString string) (*validator.Contract, *validator.ValidationResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", yamlString)
	ret0, _ := ret[0].(*validator.Contract)
	ret1, _ := ret[1].(*validator.ValidationResult)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockContractValidatorMockRecorder) Validate(yamlString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockContractValidator)(nil).Validate), yamlString)
}

// MockTimeoutMonitor is a mock of TimeoutMonitor interface.
type MockTimeoutMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockTimeoutMonitorMockRecorder
}

// MockTimeoutMonitorMockRecorder is the mock recorder for MockTimeoutMonitor.
type MockTimeoutMonitorMockRecorder struct {
	mock *MockTimeoutMonitor
}

// NewMockTimeoutMonitor creates a new mock instance.
func NewMockTimeoutMonitor(ctrl *gomock.Controller) *MockTimeoutMonitor {
	mock := &MockTimeoutMonitor{ctrl: ctrl}
	mock.recorder = &MockTimeoutMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeoutMonitor) EXPECT() *MockTimeoutMonitorMockRecorder {
	return m.recorder
}

// CancelTimeout mocks base method.
func (m *MockTimeoutMonitor) CancelTimeout(timeoutID, threadID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTimeout", timeoutID, threadID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTimeout indicates an expected call of CancelTimeout.
func (mr *MockTimeoutMonitorMockRecorder) CancelTimeout(timeoutID, threadID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTimeout", reflect.TypeOf((*MockTimeoutMonitor)(nil).CancelTimeout), timeoutID, threadID, reason)
}

// ScheduleTimeout mocks base method.
func (m *MockTimeoutMonitor) ScheduleTimeout(event models.TimeoutEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleTimeout", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScheduleTimeout indicates an expected call of ScheduleTimeout.
func (mr *MockTimeoutMonitorMockRecorder) ScheduleTimeout(event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleTimeout", reflect.TypeOf((*MockTimeoutMonitor)(nil).ScheduleTimeout), event)
}

// MockContractService is a mock of ContractService interface.
type MockContractService struct {
	ctrl     *gomock.Controller
	recorder *MockContractServiceMockRecorder
}

// MockContractServiceMockRecorder is the mock recorder for MockContractService.
type MockContractServiceMockRecorder struct {
	mock *MockContractService
}

// NewMockContractService creates a new mock instance.
func NewMockContractService(ctrl *gomock.Controller) *MockContractService {
	mock := &MockContractService{ctrl: ctrl}
	mock.recorder = &MockContractServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractService) EXPECT() *MockContractServiceMockRecorder {
	return m.recorder
}

// CreateContract mocks base method.
func (m *MockContractService) CreateContract(ctx context.Context, ownerID, companyID, createdBy, contractYAML string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContract", ctx, ownerID, companyID, createdBy, contractYAML)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// CreateContract indicates an expected call of CreateContract.
func (mr *MockContractServiceMockRecorder) CreateContract(ctx, ownerID, companyID, createdBy, contractYAML interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContract", reflect.TypeOf((*MockContractService)(nil).CreateContract), ctx, ownerID, companyID, createdBy, contractYAML)
}

// DeleteContract mocks base method.
func (m *MockContractService) DeleteContract(ctx context.Context, contractID, ownerID string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContract", ctx, contractID, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// DeleteContract indicates an expected call of DeleteContract.
func (mr *MockContractServiceMockRecorder) DeleteContract(ctx, contractID, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContract", reflect.TypeOf((*MockContractService)(nil).DeleteContract), ctx, contractID, ownerID)
}

// DeleteContractVersion mocks base method.
func (m *MockContractService) DeleteContractVersion(ctx context.Context, contractID string, version int, ownerID string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContractVersion", ctx, contractID, version, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// DeleteContractVersion indicates an expected call of DeleteContractVersion.
func (mr *MockContractServiceMockRecorder) DeleteContractVersion(ctx, contractID, version, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContractVersion", reflect.TypeOf((*MockContractService)(nil).DeleteContractVersion), ctx, contractID, version, ownerID)
}

// GetAllContractVersions mocks base method.
func (m *MockContractService) GetAllContractVersions(ctx context.Context, contractID, requesterID string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContractVersions", ctx, contractID, requesterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// GetAllContractVersions indicates an expected call of GetAllContractVersions.
func (mr *MockContractServiceMockRecorder) GetAllContractVersions(ctx, contractID, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContractVersions", reflect.TypeOf((*MockContractService)(nil).GetAllContractVersions), ctx, contractID, requesterID)
}

// GetAllContracts mocks base method.
func (m *MockContractService) GetAllContracts(ctx context.Context, ownerID string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContracts", ctx, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// GetAllContracts indicates an expected call of GetAllContracts.
func (mr *MockContractServiceMockRecorder) GetAllContracts(ctx, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContracts", reflect.TypeOf((*MockContractService)(nil).GetAllContracts), ctx, ownerID)
}

// GetContract mocks base method.
func (m *MockContractService) GetContract(ctx context.Context, contractID, requesterID string, version *int) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", ctx, contractID, requesterID, version)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// GetContract indicates an expected call of GetContract.
func (mr *MockContractServiceMockRecorder) GetContract(ctx, contractID, requesterID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockContractService)(nil).GetContract), ctx, contractID, requesterID, version)
}

// GetContractVersion mocks base method.
func (m *MockContractService) GetContractVersion(ctx context.Context, contractID string, version int, requesterID string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContractVersion", ctx, contractID, version, requesterID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// GetContractVersion indicates an expected call of GetContractVersion.
func (mr *MockContractServiceMockRecorder) GetContractVersion(ctx, contractID, version, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContractVersion", reflect.TypeOf((*MockContractService)(nil).GetContractVersion), ctx, contractID, version, requesterID)
}

// PreviewContract mocks base method.
func (m *MockContractService) PreviewContract(yamlString string) (*validator.Contract, *models.ContractGraph, *validator.ValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewContract", yamlString)
	ret0, _ := ret[0].(*validator.Contract)
	ret1, _ := ret[1].(*models.ContractGraph)
	ret2, _ := ret[2].(*validator.ValidationResult)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// PreviewContract indicates an expected call of PreviewContract.
func (mr *MockContractServiceMockRecorder) PreviewContract(yamlString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewContract", reflect.TypeOf((*MockContractService)(nil).PreviewContract), yamlString)
}

// UpdateContract mocks base method.
func (m *MockContractService) UpdateContract(ctx context.Context, contractID, ownerID, createdBy, contractYAML string) (int, interface{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContract", ctx, contractID, ownerID, createdBy, contractYAML)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	return ret0, ret1
}

// UpdateContract indicates an expected call of UpdateContract.
func (mr *MockContractServiceMockRecorder) UpdateContract(ctx, contractID, ownerID, createdBy, contractYAML interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContract", reflect.TypeOf((*MockContractService)(nil).UpdateContract), ctx, contractID, ownerID, createdBy, contractYAML)
}

// MockThreadService is a mock of ThreadService interface.
type MockThreadService struct {
	ctrl     *gomock.Controller
	recorder *MockThreadServiceMockRecorder
}

// MockThreadServiceMockRecorder is the mock recorder for MockThreadService.
type MockThreadServiceMockRecorder struct {
	mock *MockThreadService
}

// NewMockThreadService creates a new mock instance.
func NewMockThreadService(ctrl *gomock.Controller) *MockThreadService {
	mock := &MockThreadService{ctrl: ctrl}
	mock.recorder = &MockThreadServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadService) EXPECT() *MockThreadServiceMockRecorder {
	return m.recorder
}

// EndThread mocks base method.
func (m *MockThreadService) EndThread(ctx context.Context, threadID, actorID, actorService, status, reason string, recordedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndThread", ctx, threadID, actorID, actorService, status, reason, recordedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndThread indicates an expected call of EndThread.
func (mr *MockThreadServiceMockRecorder) EndThread(ctx, threadID, actorID, actorService, status, reason, recordedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndThread", reflect.TypeOf((*MockThreadService)(nil).EndThread), ctx, threadID, actorID, actorService, status, reason, recordedAt)
}

// HandleAddRefs mocks base method.
func (m *MockThreadService) HandleAddRefs(ctx context.Context, req *models.AddRefsRequest, ownerID string) *models.AddRefsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAddRefs", ctx, req, ownerID)
	ret0, _ := ret[0].(*models.AddRefsResponse)
	return ret0
}

// HandleAddRefs indicates an expected call of HandleAddRefs.
func (mr *MockThreadServiceMockRecorder) HandleAddRefs(ctx, req, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAddRefs", reflect.TypeOf((*MockThreadService)(nil).HandleAddRefs), ctx, req, ownerID)
}

// HandleClose mocks base method.
func (m *MockThreadService) HandleClose(ownerID string) *models.CloseConnectionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleClose", ownerID)
	ret0, _ := ret[0].(*models.CloseConnectionResponse)
	return ret0
}

// HandleClose indicates an expected call of HandleClose.
func (mr *MockThreadServiceMockRecorder) HandleClose(ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleClose", reflect.TypeOf((*MockThreadService)(nil).HandleClose), ownerID)
}

// HandleConnect mocks base method.
func (m *MockThreadService) HandleConnect(ctx context.Context, req *models.ConnectRequest) *models.ConnectResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConnect", ctx, req)
	ret0, _ := ret[0].(*models.ConnectResponse)
	return ret0
}

// HandleConnect indicates an expected call of HandleConnect.
func (mr *MockThreadServiceMockRecorder) HandleConnect(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnect", reflect.TypeOf((*MockThreadService)(nil).HandleConnect), ctx, req)
}

// HandleInviteParty mocks base method.
func (m *MockThreadService) HandleInviteParty(req *models.InvitePartyRequest, ownerID, companyID string, threadIDs []string) (*models.InvitePartyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInviteParty", req, ownerID, companyID, threadIDs)
	ret0, _ := ret[0].(*models.InvitePartyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleInviteParty indicates an expected call of HandleInviteParty.
func (mr *MockThreadServiceMockRecorder) HandleInviteParty(req, ownerID, companyID, threadIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInviteParty", reflect.TypeOf((*MockThreadService)(nil).HandleInviteParty), req, ownerID, companyID, threadIDs)
}

// HandleJoinThread mocks base method.
func (m *MockThreadService) HandleJoinThread(req *models.JoinThreadRequest, ownerID, companyID string) (*models.JoinThreadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleJoinThread", req, ownerID, companyID)
	ret0, _ := ret[0].(*models.JoinThreadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleJoinThread indicates an expected call of HandleJoinThread.
func (mr *MockThreadServiceMockRecorder) HandleJoinThread(req, ownerID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleJoinThread", reflect.TypeOf((*MockThreadService)(nil).HandleJoinThread), req, ownerID, companyID)
}

// HandleRecordEvent mocks base method.
func (m *MockThreadService) HandleRecordEvent(ctx context.Context, req *models.RecordEventRequest, ownerID, companyID string) *models.RecordEventResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRecordEvent", ctx, req, ownerID, companyID)
	ret0, _ := ret[0].(*models.RecordEventResponse)
	return ret0
}

// HandleRecordEvent indicates an expected call of HandleRecordEvent.
func (mr *MockThreadServiceMockRecorder) HandleRecordEvent(ctx, req, ownerID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRecordEvent", reflect.TypeOf((*MockThreadService)(nil).HandleRecordEvent), ctx, req, ownerID, companyID)
}

// HandleStartThread mocks base method.
func (m *MockThreadService) HandleStartThread(ctx context.Context, req *models.StartThreadRequest, ownerID, companyID string) *models.StartThreadResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStartThread", ctx, req, ownerID, companyID)
	ret0, _ := ret[0].(*models.StartThreadResponse)
	return ret0
}

// HandleStartThread indicates an expected call of HandleStartThread.
func (mr *MockThreadServiceMockRecorder) HandleStartThread(ctx, req, ownerID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStartThread", reflect.TypeOf((*MockThreadService)(nil).HandleStartThread), ctx, req, ownerID, companyID)
}

// MockInvitationTokenService is a mock of InvitationTokenService interface.
type MockInvitationTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationTokenServiceMockRecorder
}

// MockInvitationTokenServiceMockRecorder is the mock recorder for MockInvitationTokenService.
type MockInvitationTokenServiceMockRecorder struct {
	mock *MockInvitationTokenService
}

// NewMockInvitationTokenService creates a new mock instance.
func NewMockInvitationTokenService(ctrl *gomock.Controller) *MockInvitationTokenService {
	mock := &MockInvitationTokenService{ctrl: ctrl}
	mock.recorder = &MockInvitationTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationTokenService) EXPECT() *MockInvitationTokenServiceMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockInvitationTokenService) CreateToken(threadID, userID, role, accessLevel string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", threadID, userID, role, accessLevel, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockInvitationTokenServiceMockRecorder) CreateToken(threadID, userID, role, accessLevel, expiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockInvitationTokenService)(nil).CreateToken), threadID, userID, role, accessLevel, expiry)
}

// ParseExpiry mocks base method.
func (m *MockInvitationTokenService) ParseExpiry(expiresIn string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseExpiry", expiresIn)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseExpiry indicates an expected call of ParseExpiry.
func (mr *MockInvitationTokenServiceMockRecorder) ParseExpiry(expiresIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseExpiry", reflect.TypeOf((*MockInvitationTokenService)(nil).ParseExpiry), expiresIn)
}

// ValidateAccessLevel mocks base method.
func (m *MockInvitationTokenService) ValidateAccessLevel(accessLevel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessLevel", accessLevel)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAccessLevel indicates an expected call of ValidateAccessLevel.
func (mr *MockInvitationTokenServiceMockRecorder) ValidateAccessLevel(accessLevel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessLevel", reflect.TypeOf((*MockInvitationTokenService)(nil).ValidateAccessLevel), accessLevel)
}

// ValidateToken mocks base method.
func (m *MockInvitationTokenService) ValidateToken(tokenString string) (*models.ThreadInvitationClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*models.ThreadInvitationClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockInvitationTokenServiceMockRecorder) ValidateToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockInvitationTokenService)(nil).ValidateToken), tokenString)
}

// MockNotificationConsumer is a mock of NotificationConsumer interface.
type MockNotificationConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationConsumerMockRecorder
}

// MockNotificationConsumerMockRecorder is the mock recorder for MockNotificationConsumer.
type MockNotificationConsumerMockRecorder struct {
	mock *MockNotificationConsumer
}

// NewMockNotificationConsumer creates a new mock instance.
func NewMockNotificationConsumer(ctrl *gomock.Controller) *MockNotificationConsumer {
	mock := &MockNotificationConsumer{ctrl: ctrl}
	mock.recorder = &MockNotificationConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationConsumer) EXPECT() *MockNotificationConsumerMockRecorder {
	return m.recorder
}

// Unsubscribe mocks base method.
func (m *MockNotificationConsumer) Unsubscribe(threadID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", threadID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockNotificationConsumerMockRecorder) Unsubscribe(threadID, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockNotificationConsumer)(nil).Unsubscribe), threadID, ownerID)
}

// MockNotificationRouter is a mock of NotificationRouter interface.
type MockNotificationRouter struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRouterMockRecorder
}

// MockNotificationRouterMockRecorder is the mock recorder for MockNotificationRouter.
type MockNotificationRouterMockRecorder struct {
	mock *MockNotificationRouter
}

// NewMockNotificationRouter creates a new mock instance.
func NewMockNotificationRouter(ctrl *gomock.Controller) *MockNotificationRouter {
	mock := &MockNotificationRouter{ctrl: ctrl}
	mock.recorder = &MockNotificationRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRouter) EXPECT() *MockNotificationRouterMockRecorder {
	return m.recorder
}

// HandleAck mocks base method.
func (m *MockNotificationRouter) HandleAck(ackToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAck", ackToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAck indicates an expected call of HandleAck.
func (mr *MockNotificationRouterMockRecorder) HandleAck(ackToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAck", reflect.TypeOf((*MockNotificationRouter)(nil).HandleAck), ackToken)
}

// HandleConnect mocks base method.
func (m *MockNotificationRouter) HandleConnect(sessionID, ownerID string, maxInFlight int, conn interfaces.WSConnection, connMutex interfaces.WSMutex) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleConnect", sessionID, ownerID, maxInFlight, conn, connMutex)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleConnect indicates an expected call of HandleConnect.
func (mr *MockNotificationRouterMockRecorder) HandleConnect(sessionID, ownerID, maxInFlight, conn, connMutex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnect", reflect.TypeOf((*MockNotificationRouter)(nil).HandleConnect), sessionID, ownerID, maxInFlight, conn, connMutex)
}

// HandleDisconnect mocks base method.
func (m *MockNotificationRouter) HandleDisconnect(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDisconnect", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDisconnect indicates an expected call of HandleDisconnect.
func (mr *MockNotificationRouterMockRecorder) HandleDisconnect(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDisconnect", reflect.TypeOf((*MockNotificationRouter)(nil).HandleDisconnect), sessionID)
}

// HandleSubscribe mocks base method.
func (m *MockNotificationRouter) HandleSubscribe(sessionID, stepName, contract string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSubscribe", sessionID, stepName, contract)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSubscribe indicates an expected call of HandleSubscribe.
func (mr *MockNotificationRouterMockRecorder) HandleSubscribe(sessionID, stepName, contract interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSubscribe", reflect.TypeOf((*MockNotificationRouter)(nil).HandleSubscribe), sessionID, stepName, contract)
}

// MockNotificationPublisher is a mock of NotificationPublisher interface.
type MockNotificationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationPublisherMockRecorder
}

// MockNotificationPublisherMockRecorder is the mock recorder for MockNotificationPublisher.
type MockNotificationPublisherMockRecorder struct {
	mock *MockNotificationPublisher
}

// NewMockNotificationPublisher creates a new mock instance.
func NewMockNotificationPublisher(ctrl *gomock.Controller) *MockNotificationPublisher {
	mock := &MockNotificationPublisher{ctrl: ctrl}
	mock.recorder = &MockNotificationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationPublisher) EXPECT() *MockNotificationPublisherMockRecorder {
	return m.recorder
}

// PublishNotification mocks base method.
func (m *MockNotificationPublisher) PublishNotification(ctx context.Context, notification models.ValidationNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishNotification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishNotification indicates an expected call of PublishNotification.
func (mr *MockNotificationPublisherMockRecorder) PublishNotification(ctx, notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishNotification", reflect.TypeOf((*MockNotificationPublisher)(nil).PublishNotification), ctx, notification)
}

// MockWSConnection is a mock of WSConnection interface.
type MockWSConnection struct {
	ctrl     *gomock.Controller
	recorder *MockWSConnectionMockRecorder
}

// MockWSConnectionMockRecorder is the mock recorder for MockWSConnection.
type MockWSConnectionMockRecorder struct {
	mock *MockWSConnection
}

// NewMockWSConnection creates a new mock instance.
func NewMockWSConnection(ctrl *gomock.Controller) *MockWSConnection {
	mock := &MockWSConnection{ctrl: ctrl}
	mock.recorder = &MockWSConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSConnection) EXPECT() *MockWSConnectionMockRecorder {
	return m.recorder
}

// WriteJSON mocks base method.
func (m *MockWSConnection) WriteJSON(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJSON", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJSON indicates an expected call of WriteJSON.
func (mr *MockWSConnectionMockRecorder) WriteJSON(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJSON", reflect.TypeOf((*MockWSConnection)(nil).WriteJSON), v)
}

// MockWSMutex is a mock of WSMutex interface.
type MockWSMutex struct {
	ctrl     *gomock.Controller
	recorder *MockWSMutexMockRecorder
}

// MockWSMutexMockRecorder is the mock recorder for MockWSMutex.
type MockWSMutexMockRecorder struct {
	mock *MockWSMutex
}

// NewMockWSMutex creates a new mock instance.
func NewMockWSMutex(ctrl *gomock.Controller) *MockWSMutex {
	mock := &MockWSMutex{ctrl: ctrl}
	mock.recorder = &MockWSMutexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSMutex) EXPECT() *MockWSMutexMockRecorder {
	return m.recorder
}

// Lock mocks base method.
func (m *MockWSMutex) Lock() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Lock")
}

// Lock indicates an expected call of Lock.
func (mr *MockWSMutexMockRecorder) Lock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockWSMutex)(nil).Lock))
}

// Unlock mocks base method.
func (m *MockWSMutex) Unlock() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unlock")
}

// Unlock indicates an expected call of Unlock.
func (mr *MockWSMutexMockRecorder) Unlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockWSMutex)(nil).Unlock))
}
