// Code generated by MockGen. DO NOT EDIT.
// Source: step_state_repository.go

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/threadify/engine/internal/domain"
)

// MockStepStateRepository is a mock of StepStateRepository interface.
type MockStepStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStepStateRepositoryMockRecorder
}

// MockStepStateRepositoryMockRecorder is the mock recorder for MockStepStateRepository.
type MockStepStateRepositoryMockRecorder struct {
	mock *MockStepStateRepository
}

// NewMockStepStateRepository creates a new mock instance.
func NewMockStepStateRepository(ctrl *gomock.Controller) *MockStepStateRepository {
	mock := &MockStepStateRepository{ctrl: ctrl}
	mock.recorder = &MockStepStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepStateRepository) EXPECT() *MockStepStateRepositoryMockRecorder {
	return m.recorder
}

// LoadScripts mocks base method.
func (m *MockStepStateRepository) LoadScripts(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadScripts", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadScripts indicates an expected call of LoadScripts.
func (mr *MockStepStateRepositoryMockRecorder) LoadScripts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadScripts", reflect.TypeOf((*MockStepStateRepository)(nil).LoadScripts), ctx)
}

// ValidateAndUpdateStepState mocks base method.
func (m *MockStepStateRepository) ValidateAndUpdateStepState(ctx context.Context, params domain.ValidateStepParams) (*domain.StepStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndUpdateStepState", ctx, params)
	ret0, _ := ret[0].(*domain.StepStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndUpdateStepState indicates an expected call of ValidateAndUpdateStepState.
func (mr *MockStepStateRepositoryMockRecorder) ValidateAndUpdateStepState(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndUpdateStepState", reflect.TypeOf((*MockStepStateRepository)(nil).ValidateAndUpdateStepState), ctx, params)
}
