"""Materialize shared Nanites sources into independently compiled agents."""

from __future__ import annotations

import argparse
import hashlib
import shutil
from pathlib import Path

_ROOT = Path(__file__).resolve().parent
_EXTENSION_SOURCE = _ROOT.parents[1] / "threadify-agent" / "extensions" / "threadify"
_AGENTS = ("dispatcher", "analyst", "reviewer")
_WORKERS = frozenset({"analyst", "reviewer"})
_MARKER = ".threadify.nanites-generated"


def materialize(root: Path = _ROOT, extension_source: Path = _EXTENSION_SOURCE) -> None:
    """Refresh generated copies while protecting any user-owned extension folder."""

    _require_source(extension_source, "Threadify extension")
    shared = root / "shared"
    _require_source(shared, "Nanites shared source")
    for name in _AGENTS:
        agent = root / name
        _replace_extension(extension_source, agent / "extensions" / "threadify")
        _copy_shared(shared / "nanite_model.py", agent / "lib" / "nanite_model.py")
        _copy_shared(
            shared / "nanite_storage.py",
            agent / "lifecycle" / "storage.py",
        )
        if name in _WORKERS:
            _copy_shared(
                shared / "nanite_worker.py",
                agent / "lib" / "nanite_worker.py",
            )


def check(root: Path = _ROOT, extension_source: Path = _EXTENSION_SOURCE) -> bool:
    """Report whether every generated file matches its single source of truth."""

    expected_extension = _tree_digest(extension_source)
    shared = root / "shared"
    for name in _AGENTS:
        agent = root / name
        extension = agent / "extensions" / "threadify"
        if not _marker(extension).is_file():
            return False
        if _tree_digest(extension) != expected_extension:
            return False
        if not _same_file(shared / "nanite_model.py", agent / "lib" / "nanite_model.py"):
            return False
        if not _same_file(
            shared / "nanite_storage.py", agent / "lifecycle" / "storage.py"
        ):
            return False
        if name in _WORKERS and not _same_file(
            shared / "nanite_worker.py", agent / "lib" / "nanite_worker.py"
        ):
            return False
    return True



def _replace_extension(source: Path, destination: Path) -> None:
    """Replace only directories previously marked as generated by this example."""

    if destination.exists():
        sibling = destination.parent / _MARKER
        owned = _marker(destination).is_file() or sibling.is_file()
        if not owned:
            raise RuntimeError(f"refusing to replace user-owned extension: {destination}")
        shutil.rmtree(destination)
        sibling.unlink(missing_ok=True)
    shutil.copytree(source, destination, ignore=_ignored)
    marker = _marker(destination)
    marker.parent.mkdir(parents=True, exist_ok=True)
    marker.write_text("generated by prepare.py\n", encoding="utf-8")


def _marker(destination: Path) -> Path:
    """Keep generator ownership outside every independently compiled agent."""

    agent = destination.parents[1]
    return agent.parent / ".generated" / f"{agent.name}-threadify"


def _copy_shared(source: Path, destination: Path) -> None:
    """Copy one visible shared source into the agent compiler namespace."""

    if not source.is_file():
        raise FileNotFoundError(f"shared Nanites source is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def _require_source(path: Path, label: str) -> None:
    """Fail before partially updating agents when a shared source is absent."""

    if not path.is_dir():
        raise FileNotFoundError(f"{label} is missing: {path}")


def _ignored(_directory: str, names: list[str]) -> set[str]:
    """Keep transient Python artifacts out of materialized agent sources."""

    return {name for name in names if name == "__pycache__" or name.endswith(".pyc")}


def _tree_digest(root: Path, ignored: frozenset[str] = frozenset()) -> str:
    """Hash generated source deterministically without loading whole files."""

    digest = hashlib.sha256()
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        if path.name in ignored or "__pycache__" in path.parts:
            continue
        relative = path.relative_to(root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(8, "big"))
        digest.update(relative)
        with path.open("rb") as source:
            while chunk := source.read(1024 * 1024):
                digest.update(chunk)
    return digest.hexdigest()


def _same_file(source: Path, destination: Path) -> bool:
    """Compare one generated file without trusting modification timestamps."""

    if not source.is_file() or not destination.is_file():
        return False
    return _file_digest(source) == _file_digest(destination)


def _file_digest(path: Path) -> str:
    """Hash one source stream for generation checks."""

    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str] | None = None) -> int:
    """Refresh by default or fail when ``--check`` detects stale copies."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    if arguments.check:
        return 0 if check() else 1
    materialize()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
