// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/shared/management/ports (interfaces: RBACRoleLoader)

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRBACRoleLoader is a mock of RBACRoleLoader interface.
type MockRBACRoleLoader struct {
	ctrl     *gomock.Controller
	recorder *MockRBACRoleLoaderMockRecorder
}

// MockRBACRoleLoaderMockRecorder is the mock recorder for MockRBACRoleLoader.
type MockRBACRoleLoaderMockRecorder struct {
	mock *MockRBACRoleLoader
}

// NewMockRBACRoleLoader creates a new mock instance.
func NewMockRBACRoleLoader(ctrl *gomock.Controller) *MockRBACRoleLoader {
	mock := &MockRBACRoleLoader{ctrl: ctrl}
	mock.recorder = &MockRBACRoleLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACRoleLoader) EXPECT() *MockRBACRoleLoaderMockRecorder {
	return m.recorder
}

// GetRolesByLevel mocks base method.
func (m *MockRBACRoleLoader) GetRolesByLevel(arg0 string) map[string]struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByLevel", arg0)
	ret0, _ := ret[0].(map[string]struct{})
	return ret0
}

// GetRolesByLevel indicates an expected call of GetRolesByLevel.
func (mr *MockRBACRoleLoaderMockRecorder) GetRolesByLevel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByLevel", reflect.TypeOf((*MockRBACRoleLoader)(nil).GetRolesByLevel), arg0)
}
