// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/api/internal/interfaces (interfaces: ServiceAccountService)

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	models "threadify-go/api/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceAccountService is a mock of ServiceAccountService interface.
type MockServiceAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountServiceMockRecorder
}

// MockServiceAccountServiceMockRecorder is the mock recorder for MockServiceAccountService.
type MockServiceAccountServiceMockRecorder struct {
	mock *MockServiceAccountService
}

// NewMockServiceAccountService creates a new mock instance.
func NewMockServiceAccountService(ctrl *gomock.Controller) *MockServiceAccountService {
	mock := &MockServiceAccountService{ctrl: ctrl}
	mock.recorder = &MockServiceAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountService) EXPECT() *MockServiceAccountServiceMockRecorder {
	return m.recorder
}

// CreateServiceAccount mocks base method.
func (m *MockServiceAccountService) CreateServiceAccount(arg0 context.Context, arg1, arg2 string, arg3 *models.CreateServiceAccountRequest) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) CreateServiceAccount(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).CreateServiceAccount), arg0, arg1, arg2, arg3)
}

// DeleteServiceAccount mocks base method.
func (m *MockServiceAccountService) DeleteServiceAccount(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) DeleteServiceAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).DeleteServiceAccount), arg0, arg1, arg2)
}

// GetServiceAccount mocks base method.
func (m *MockServiceAccountService) GetServiceAccount(arg0 context.Context, arg1, arg2 string) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) GetServiceAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).GetServiceAccount), arg0, arg1, arg2)
}

// ListServiceAccounts mocks base method.
func (m *MockServiceAccountService) ListServiceAccounts(arg0 context.Context, arg1 string) ([]*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccounts", arg0, arg1)
	ret0, _ := ret[0].([]*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccounts indicates an expected call of ListServiceAccounts.
func (mr *MockServiceAccountServiceMockRecorder) ListServiceAccounts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccounts", reflect.TypeOf((*MockServiceAccountService)(nil).ListServiceAccounts), arg0, arg1)
}

// UpdateServiceAccount mocks base method.
func (m *MockServiceAccountService) UpdateServiceAccount(arg0 context.Context, arg1, arg2 string, arg3 *models.UpdateServiceAccountRequest) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceAccount", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceAccount indicates an expected call of UpdateServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) UpdateServiceAccount(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).UpdateServiceAccount), arg0, arg1, arg2, arg3)
}
