// Code generated by MockGen. DO NOT EDIT.
// Source: timeout_monitor.go

// Package timeoutmocks is a generated GoMock package.
package timeoutmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
)

// MocktimeoutKV is a mock of timeoutKV interface.
type MocktimeoutKV struct {
	ctrl     *gomock.Controller
	recorder *MocktimeoutKVMockRecorder
}

// MocktimeoutKVMockRecorder is the mock recorder for MocktimeoutKV.
type MocktimeoutKVMockRecorder struct {
	mock *MocktimeoutKV
}

// NewMocktimeoutKV creates a new mock instance.
func NewMocktimeoutKV(ctrl *gomock.Controller) *MocktimeoutKV {
	mock := &MocktimeoutKV{ctrl: ctrl}
	mock.recorder = &MocktimeoutKVMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeoutKV) EXPECT() *MocktimeoutKVMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocktimeoutKV) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocktimeoutKVMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocktimeoutKV)(nil).Get), ctx, key)
}

// Put mocks base method.
func (m *MocktimeoutKV) Put(ctx context.Context, key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MocktimeoutKVMockRecorder) Put(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MocktimeoutKV)(nil).Put), ctx, key, value)
}
