package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/threadify/engine/internal/graphql/generated"
	"github.com/threadify/engine/internal/models"
	apperrors "github.com/threadify/engine/internal/utils/errors"
)

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*models.Thread, error) {
	// Use the cached repository for thread retrieval
	thread, err := r.threadRepo.GetThreadWithCache(ctx, id)
	if err != nil {
		// Return user-friendly error without exposing internal details
		if apperrors.IsNotFound(err) {
			return nil, err // Already wrapped with user-friendly message
		}
		// Wrap other errors with generic message
		return nil, apperrors.NewInternalError(apperrors.MsgInternalError, err)
	}
	return thread, nil
}

// StepHistory is the resolver for the stepHistory field.
func (r *queryResolver) StepHistory(ctx context.Context, threadID string, stepName string, idempotencyKey *string, limit *int, offset *int, startAt *string, endAt *string, activityType *string, actor *string) ([]*models.StepHistory, error) {
	// Set default pagination values
	limitVal := 100
	offsetVal := 0

	if limit != nil {
		limitVal = *limit
	}
	if offset != nil {
		offsetVal = *offset
	}

	// Construct step identifier
	var stepIdentifier string
	if idempotencyKey != nil && *idempotencyKey != "" {
		// Specific step: stepName:idempKey
		stepIdentifier = fmt.Sprintf("%s:%s", stepName, *idempotencyKey)
	} else {
		// All attempts of step: stepName
		stepIdentifier = stepName
	}

	// Get step history from PostgreSQL with enhanced filtering
	history, err := r.stepStateRepo.GetStepHistory(ctx, threadID, stepIdentifier, limitVal, offsetVal, startAt, endAt, activityType, actor)
	if err != nil {
		return nil, fmt.Errorf("failed to get step history: %w", err)
	}

	// Return empty array if no history found (better UX than error)
	if history == nil {
		return []*models.StepHistory{}, nil
	}

	// Convert slice of values to slice of pointers for GraphQL
	var historyPtrs []*models.StepHistory
	for i := range history {
		historyPtrs = append(historyPtrs, &history[i])
	}

	return historyPtrs, nil
}

// ValidationResults is the resolver for the validationResults field.
func (r *queryResolver) ValidationResults(ctx context.Context, threadID string, stepName string, idempotencyKey string) ([]*models.ValidationResultInfo, error) {
	return r.validationRepo.GetValidationResultsWithCache(ctx, threadID, stepName, idempotencyKey)
}

// FirstSeenAt is the resolver for the firstSeenAt field.
func (r *stepStateInfoResolver) FirstSeenAt(ctx context.Context, obj *models.StepStateInfo) (string, error) {
	return obj.FirstSeenAt.Format(time.RFC3339), nil
}

// LastUpdatedAt is the resolver for the lastUpdatedAt field.
func (r *stepStateInfoResolver) LastUpdatedAt(ctx context.Context, obj *models.StepStateInfo) (string, error) {
	return obj.LastUpdatedAt.Format(time.RFC3339), nil
}

// History is the resolver for the history field.
func (r *stepStateInfoResolver) History(ctx context.Context, obj *models.StepStateInfo, limit *int, offset *int, startAt *string, endAt *string, activityType *string, actor *string) ([]*models.StepHistory, error) {
	// Set default pagination values
	limitVal := 100
	offsetVal := 0

	if limit != nil {
		limitVal = *limit
	}
	if offset != nil {
		offsetVal = *offset
	}

	// Use step name as identifier (will get all idempotency keys for this step)
	// Users can call this on a specific step instance to get that instance's history
	stepIdentifier := obj.StepName
	if obj.IdempotencyKey != "" {
		stepIdentifier = fmt.Sprintf("%s:%s", obj.StepName, obj.IdempotencyKey)
	}

	// Get step history from PostgreSQL with enhanced filtering
	history, err := r.stepStateRepo.GetStepHistory(ctx, obj.ThreadID, stepIdentifier, limitVal, offsetVal, startAt, endAt, activityType, actor)
	if err != nil {
		return nil, fmt.Errorf("failed to get step history: %w", err)
	}

	// Return empty array if no history found (better UX than error)
	if history == nil {
		return []*models.StepHistory{}, nil
	}

	// Convert slice of values to slice of pointers for GraphQL
	var historyPtrs []*models.StepHistory
	for i := range history {
		historyPtrs = append(historyPtrs, &history[i])
	}

	return historyPtrs, nil
}

// Status is the resolver for the status field.
func (r *threadResolver) Status(ctx context.Context, obj *models.Thread) (string, error) {
	status := string(obj.Status)
	return status, nil
}

// Refs is the resolver for the refs field.
func (r *threadResolver) Refs(ctx context.Context, obj *models.Thread) (*string, error) {
	if obj.Refs == nil {
		return nil, nil
	}
	refsJSON, err := json.Marshal(obj.Refs)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal refs: %w", err)
	}
	refsStr := string(refsJSON)
	return &refsStr, nil
}

// StartedAt is the resolver for the startedAt field.
func (r *threadResolver) StartedAt(ctx context.Context, obj *models.Thread) (*string, error) {
	startedAt := obj.StartedAt.Format(time.RFC3339)
	return &startedAt, nil
}

// CompletedAt is the resolver for the completedAt field.
func (r *threadResolver) CompletedAt(ctx context.Context, obj *models.Thread) (*string, error) {
	if obj.CompletedAt == nil {
		return nil, nil
	}
	completedAt := obj.CompletedAt.Format(time.RFC3339)
	return &completedAt, nil
}

// Steps is the resolver for the steps field.
func (r *threadResolver) Steps(ctx context.Context, obj *models.Thread, stepName *string, idempotencyKey *string) ([]*models.StepStateInfo, error) {
	// Use the step state repository to list all steps for this thread
	steps, err := r.stepStateRepo.ListSteps(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list steps for thread %s: %w", obj.ID, err)
	}

	// Apply filtering if stepName is provided
	if stepName != nil {
		var filteredSteps []*models.StepStateInfo
		for _, step := range steps {
			// Filter by stepName
			if step.StepName != *stepName {
				continue
			}

			// If idempotencyKey is also provided, filter by that too
			if idempotencyKey != nil && *idempotencyKey != "" {
				if step.IdempotencyKey != *idempotencyKey {
					continue
				}
			}

			filteredSteps = append(filteredSteps, step)
		}
		return filteredSteps, nil
	}

	// If no stepName filter, return all steps
	return steps, nil
}

// ValidationResults is the resolver for the validationResults field.
func (r *threadResolver) ValidationResults(ctx context.Context, obj *models.Thread, options *models.ValidationQueryOptions) ([]*models.ValidationResultInfo, error) {
	return r.validationRepo.GetThreadValidationResultsWithCache(ctx, obj.ID, options)
}

// Timestamp is the resolver for the timestamp field.
func (r *validationResultInfoResolver) Timestamp(ctx context.Context, obj *models.ValidationResultInfo) (string, error) {
	return obj.Timestamp.Format(time.RFC3339), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// StepStateInfo returns generated.StepStateInfoResolver implementation.
func (r *Resolver) StepStateInfo() generated.StepStateInfoResolver { return &stepStateInfoResolver{r} }

// Thread returns generated.ThreadResolver implementation.
func (r *Resolver) Thread() generated.ThreadResolver { return &threadResolver{r} }

// ValidationResultInfo returns generated.ValidationResultInfoResolver implementation.
func (r *Resolver) ValidationResultInfo() generated.ValidationResultInfoResolver {
	return &validationResultInfoResolver{r}
}

type queryResolver struct{ *Resolver }
type stepStateInfoResolver struct{ *Resolver }
type threadResolver struct{ *Resolver }
type validationResultInfoResolver struct{ *Resolver }
