package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	shderrors "threadify-go/shared/errors"
	"time"

	"github.com/threadify/engine/internal/graphql/generated"
	"github.com/threadify/engine/internal/metrics"
	"github.com/threadify/engine/internal/models"
	"github.com/threadify/engine/internal/perf"
	"github.com/threadify/engine/internal/service"
	apperrors "github.com/threadify/engine/internal/utils/errors"
	"go.uber.org/zap"
)

// Nodes is the resolver for the Graph.nodes field - converts nodes map to array for GraphQL
func (r *graphResolver) Nodes(ctx context.Context, obj *models.Graph) ([]*models.GraphNode, error) {
	// Convert map[string]GraphNode to []*GraphNode array for GraphQL
	nodes := make([]*models.GraphNode, 0, len(obj.Nodes))
	for _, node := range obj.Nodes {
		// Create a copy to avoid pointer issues
		nodeCopy := node
		nodes = append(nodes, &nodeCopy)
	}
	return nodes, nil
}

// BusinessContext is the resolver for the businessContext field.
func (r *graphNodeResolver) BusinessContext(ctx context.Context, obj *models.GraphNode) (*string, error) {
	if obj.BusinessContext == nil {
		return nil, nil
	}
	businessContextJSON, err := json.Marshal(obj.BusinessContext)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal businessContext: %w", err)
	}
	businessContextStr := string(businessContextJSON)
	return &businessContextStr, nil
}

// LastVerifiedAt is the resolver for the lastVerifiedAt field.
func (r *hashChainStatusResolver) LastVerifiedAt(ctx context.Context, obj *models.HashChainStatus) (string, error) {
	// Return current timestamp as verification happens on-demand
	return time.Now().UTC().Format(time.RFC3339Nano), nil
}

// BrokenAt is the resolver for the brokenAt field.
func (r *hashChainStatusResolver) BrokenAt(ctx context.Context, obj *models.HashChainStatus) (*string, error) {
	// Return nil if verification passed, otherwise return error timestamp
	if obj.Verified {
		return nil, nil
	}
	// If verification failed, return current timestamp
	brokenAt := time.Now().UTC().Format(time.RFC3339Nano)
	return &brokenAt, nil
}

// RecordLLMUsage is the resolver for the recordLLMUsage mutation.
func (r *mutationResolver) RecordLLMUsage(ctx context.Context, tokens int) (bool, error) {
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %w", err)
	}

	if err := r.planService.DecrementLLMUsage(ctx, companyID, int64(tokens)); err != nil {
		return false, fmt.Errorf("failed to record LLM usage: %w", err)
	}

	return true, nil
}

// RoleDefaults is the resolver for the roleDefaults field.
func (r *notificationConfigResolver) RoleDefaults(ctx context.Context, obj *models.NotificationConfig) (*string, error) {
	if obj.RoleDefaults == nil {
		return nil, nil
	}
	roleDefaultsJSON, err := json.Marshal(obj.RoleDefaults)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal roleDefaults: %w", err)
	}
	roleDefaultsStr := string(roleDefaultsJSON)
	return &roleDefaultsStr, nil
}

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*models.Thread, error) {
	start := perf.Now()
	defer func() {
		metrics.RequestDuration.WithLabelValues("graphql_thread").Observe(perf.Since(start).Seconds())
	}()

	// Get user info from context
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		metrics.RequestsTotal.WithLabelValues("graphql_thread", "error").Inc()
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		metrics.RequestsTotal.WithLabelValues("graphql_thread", "error").Inc()
		return nil, err
	}

	thread, err := r.threadRepo.GetThreadWithPermissionCheck(ctx, id, companyID)
	if err != nil {
		metrics.RequestsTotal.WithLabelValues("graphql_thread", "error").Inc()
		// Return user-friendly error for access denied
		if errors.Is(err, shderrors.ErrAccessDenied) {
			return nil, fmt.Errorf("access denied: you don't have permission to view this thread")
		}
		// Return not found errors as-is
		if apperrors.IsNotFound(err) {
			return nil, err
		}
		// Return other errors as-is (database errors, connection errors, etc.)
		return nil, fmt.Errorf("failed to get thread: %w", err)
	}

	// Cache the access check result for child resolvers (steps, validationResults, etc.)
	ctx = cacheAccessCheck(ctx, thread.ID, true)
	metrics.RequestsTotal.WithLabelValues("graphql_thread", "success").Inc()
	return thread, nil
}

// Threads is the resolver for the threads field.
func (r *queryResolver) Threads(ctx context.Context, actor *string, contractName *string, contractVersion *int, status *string, startedAfter *string, startedBefore *string, completedAfter *string, completedBefore *string, limit *int, offset *int) (*models.ThreadConnection, error) {
	resolverStart := perf.Now()
	perf.Log("\n[PERF] ========== Threads() Resolver START ==========\n")
	defer func() {
		perf.Log("[PERF] ========== Threads() Resolver TOTAL: %v ==========\n\n", perf.Since(resolverStart))
		metrics.RequestDuration.WithLabelValues("graphql_threads").Observe(perf.Since(resolverStart).Seconds())
	}()

	// Get user info from context (companyID for security)
	authStart := perf.Now()
	ownerID, companyID, _, err := getUserInfoFromContext(ctx)
	perf.Log("[PERF] Threads.getUserInfo: %v\n", perf.Since(authStart))
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		return nil, err
	}

	// Normalize pagination using helper
	limitVal, offsetVal := NormalizePagination(&ThreadQueryOptions{Limit: limit, Offset: offset})

	// Get postgres repository
	postgresRepo := r.threadRepo.GetPostgresRepo()
	if postgresRepo == nil {
		return nil, apperrors.NewInternalError("Postgres repository not available", nil)
	}

	// Query threads with SQL-based access filtering (includes archived data)
	queryStart := perf.Now()
	threads, totalCount, err := postgresRepo.QueryThreadsWithAccess(ctx, companyID, ownerID, actor, contractName, contractVersion, status, startedAfter, startedBefore, completedAfter, completedBefore, limitVal, offsetVal)
	perf.Log("[PERF] Threads.QueryThreadsWithAccess: %v (returned %d threads, total: %d)\n", perf.Since(queryStart), len(threads), totalCount)

	if err != nil {
		r.logger.Error("failed to query threads",
			zap.String("company_id", companyID),
			zap.String("owner_id", ownerID),
			zap.Error(err),
		)
		return nil, apperrors.NewInternalError("Failed to query threads with access", err)
	}

	// Batch load refs (no access filtering needed - already done in SQL)
	if len(threads) > 0 {
		if err := r.BatchLoadThreadData(ctx, threads); err != nil {
			return nil, err
		}
	}

	return &models.ThreadConnection{
		Threads:    threads,
		TotalCount: totalCount,
	}, nil
}

// ThreadsByContract is the resolver for the threadsByContract field.
func (r *queryResolver) ThreadsByContract(ctx context.Context, contractName string, contractVersion *int, actor *string, status *string, startedAfter *string, startedBefore *string, limit *int, offset *int) (*models.ThreadConnection, error) {
	// Get user info from context
	ownerID, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		return nil, err
	}

	// Normalize pagination
	limitVal, offsetVal := NormalizePagination(&ThreadQueryOptions{Limit: limit, Offset: offset})

	// Get postgres repository
	postgresRepo := r.threadRepo.GetPostgresRepo()
	if postgresRepo == nil {
		return nil, apperrors.NewInternalError("Postgres repository not available", nil)
	}

	// Query threads with SQL-based access filtering
	threads, totalCount, err := postgresRepo.QueryThreadsWithAccess(ctx, companyID, ownerID, actor, &contractName, contractVersion, status, startedAfter, startedBefore, nil, nil, limitVal, offsetVal)
	if err != nil {
		r.logger.Error("failed to query threads by contract",
			zap.String("company_id", companyID),
			zap.String("owner_id", ownerID),
			zap.String("contract_name", contractName),
			zap.Error(err),
		)
		return nil, apperrors.NewInternalError("Failed to query threads by contract", err)
	}

	// Batch load refs if needed
	if len(threads) > 0 {
		if err := r.BatchLoadThreadData(ctx, threads); err != nil {
			return nil, err
		}
	}

	return &models.ThreadConnection{
		Threads:    threads,
		TotalCount: totalCount,
	}, nil
}

// ThreadsByRef is the resolver for the threadsByRef field.
func (r *queryResolver) ThreadsByRef(ctx context.Context, refKey *string, refValue string, status *string, startedAfter *string, startedBefore *string, limit *int, offset *int) (*models.ThreadConnection, error) {
	// Get user info from context (companyID for security)
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		return nil, err
	}

	// Normalize pagination
	limitVal, offsetVal := NormalizePagination(&ThreadQueryOptions{Limit: limit, Offset: offset})

	// Get postgres repository
	postgresRepo := r.threadRepo.GetPostgresRepo()
	if postgresRepo == nil {
		return nil, apperrors.NewInternalError("Postgres repository not available", nil)
	}

	// Convert refKey pointer to string (empty string if nil)
	refKeyVal := ""
	if refKey != nil {
		refKeyVal = *refKey
	}

	// Query threads by ref (this method already filters by company)
	threads, totalCount, err := postgresRepo.GetThreadsByRefWithFilters(ctx, companyID, refKeyVal, refValue, status, startedAfter, startedBefore, limitVal, offsetVal)
	if err != nil {
		r.logger.Error("failed to query threads by ref",
			zap.String("company_id", companyID),
			zap.String("ref_key", refKeyVal),
			zap.String("ref_value", refValue),
			zap.Error(err),
		)
		return nil, apperrors.NewInternalError("Failed to query threads by ref", err)
	}

	// Batch load refs if needed
	if len(threads) > 0 {
		if err := r.BatchLoadThreadData(ctx, threads); err != nil {
			return nil, err
		}
	}

	return &models.ThreadConnection{
		Threads:    threads,
		TotalCount: totalCount,
	}, nil
}

// ThreadChain is the resolver for the threadChain field.
func (r *queryResolver) ThreadChain(ctx context.Context, rootID string, maxDepth *int) ([]*models.Thread, error) {
	// Get user info from context
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		return nil, err
	}

	// Set default max depth
	depthVal := 3
	if maxDepth != nil {
		depthVal = *maxDepth
		if depthVal <= 0 || depthVal > 10 {
			return nil, fmt.Errorf("maxDepth must be between 1 and 10")
		}
	}

	// Get postgres repository
	postgresRepo := r.threadRepo.GetPostgresRepo()
	if postgresRepo == nil {
		return nil, apperrors.NewInternalError("Postgres repository not available", nil)
	}

	// SQL-level permission check with recursive CTE
	// Permission check happens at each level of the chain
	threads, err := postgresRepo.GetThreadChainWithPermissionCheck(ctx, rootID, companyID, &depthVal)
	if err != nil {
		r.logger.Error("failed to query thread chain",
			zap.String("root_id", rootID),
			zap.String("company_id", companyID),
			zap.Error(err),
		)
		return nil, apperrors.NewInternalError("Failed to query thread chain", err)
	}

	return threads, nil
}

// ContractGraph is the resolver for the contractGraph field.
func (r *queryResolver) ContractGraph(ctx context.Context, name string, version *int) (*models.ContractGraph, error) {
	r.logger.Info("ContractGraph resolver called",
		zap.String("name", name),
		zap.Any("version", version))

	// Get user info from context for authentication check
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		r.logger.Error("Failed to get user info from context", zap.Error(err))
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	r.logger.Info("User authenticated for contract graph",
		zap.String("company_id", companyID),
		zap.String("contract_name", name))

	// Handle null version - default to 0 (latest version)
	ver := 0
	if version != nil {
		ver = *version
	}

	r.logger.Info("Calling GetContractGraph",
		zap.String("name", name),
		zap.Int("version", ver),
		zap.String("company_id", companyID))

	// Use ContractValidationService to get contract graph with three-tier fallback
	// version=0 will resolve to latest version automatically
	graph, err := r.contractValidator.GetContractGraph(name, ver, companyID)
	if err != nil {
		r.logger.Error("GetContractGraph failed",
			zap.String("name", name),
			zap.Int("version", ver),
			zap.String("company_id", companyID),
			zap.Error(err))
		return nil, apperrors.NewInternalError("Failed to load contract graph", err)
	}

	r.logger.Info("Contract graph loaded successfully",
		zap.String("name", name),
		zap.Int("version", ver))

	// No additional access control needed - GetContractGraph now handles ownership validation
	return graph, nil
}

// StepHistory is the resolver for the stepHistory field.
func (r *queryResolver) StepHistory(ctx context.Context, threadID string, stepName string, idempotencyKey *string, limit *int, offset *int, startAt *string, endAt *string, activityType *string, actor *string) ([]*models.StepHistory, error) {
	// Get user info from context
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}
	if err := r.requireCredit(ctx, companyID); err != nil {
		return nil, err
	}

	// Enforce hard caps on pagination limits
	limitVal := EnforceLimit(limit, MaxHistoryPerQuery, 100)
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}

	// Construct step identifier
	var stepIdentifier string
	if idempotencyKey != nil && *idempotencyKey != "" {
		// Specific step: stepName:idempKey
		stepIdentifier = fmt.Sprintf("%s:%s", stepName, *idempotencyKey)
	} else {
		// All attempts of step: stepName
		stepIdentifier = stepName
	}

	// SQL-level permission check: company-wide access with cross-company sharing
	history, err := r.stepStateRepo.GetStepHistoryWithPermissionCheck(ctx, threadID, companyID, stepIdentifier, limitVal, offsetVal, startAt, endAt, activityType, actor)
	if err != nil {
		r.logger.Error("failed to get step history",
			zap.String("thread_id", threadID),
			zap.String("company_id", companyID),
			zap.Error(err),
		)
		return nil, fmt.Errorf("failed to get step history: %w", err)
	}

	// Return empty array if no history found (better UX than error)
	if history == nil {
		return []*models.StepHistory{}, nil
	}

	// Convert slice of values to slice of pointers for GraphQL
	var historyPtrs []*models.StepHistory
	for i := range history {
		historyPtrs = append(historyPtrs, &history[i])
	}

	return historyPtrs, nil
}

// ValidationResults is the resolver for the validationResults field.
func (r *queryResolver) ValidationResults(ctx context.Context, threadID string, stepName string, idempotencyKey string) ([]*models.ValidationResultInfo, error) {
	return r.validationRepo.GetValidationResultsWithCache(ctx, threadID, stepName, idempotencyKey)
}

// ResolveActors is the resolver for the resolveActors field.
func (r *queryResolver) ResolveActors(ctx context.Context, ids []string) ([]*models.ActorInfo, error) {
	return r.actorRepo.ResolveActors(ctx, ids)
}

// VerifyThreadIntegrity is the resolver for the verifyThreadIntegrity query
// Verifies the hash chain integrity of a thread (separate from thread query for performance)
func (r *queryResolver) VerifyThreadIntegrity(ctx context.Context, threadID string) (*models.HashChainStatus, error) {
	// Call the activity repository to verify the chain
	status, err := r.activityRepo.VerifyActivityChain(ctx, threadID)
	if err != nil {
		r.logger.Error("failed to verify thread integrity",
			zap.String("thread_id", threadID),
			zap.Error(err),
		)
		return nil, fmt.Errorf("failed to verify thread integrity: %w", err)
	}
	return status, nil
}

// Verifies the hash integrity of a single step
func (r *queryResolver) VerifyStepIntegrity(ctx context.Context, threadID string, stepName string, idempotencyKey string) (*models.StepIntegrityStatus, error) {
	// Get the step hashes
	hash, prevHash, err := r.activityRepo.GetStepHashes(ctx, threadID, stepName, idempotencyKey)
	if err != nil {
		r.logger.Error("failed to get step hashes",
			zap.String("thread_id", threadID),
			zap.String("step_name", stepName),
			zap.Error(err),
		)
		return nil, fmt.Errorf("failed to get step hashes: %w", err)
	}

	// Verify the step hash
	verified, errMsg, err := r.activityRepo.VerifyStepHash(ctx, threadID, stepName, idempotencyKey)
	if err != nil {
		r.logger.Error("failed to verify step hash",
			zap.String("thread_id", threadID),
			zap.String("step_name", stepName),
			zap.Error(err),
		)
		return nil, fmt.Errorf("failed to verify step hash: %w", err)
	}

	status := &models.StepIntegrityStatus{
		Verified: verified,
		Hash:     hash,
		PrevHash: prevHash,
	}

	if errMsg != "" {
		status.Error = &errMsg
	}

	return status, nil
}

// CheckCredits is the resolver for the checkCredits query.
func (r *queryResolver) CheckCredits(ctx context.Context, meter *string, amount *int) (bool, error) {
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return false, fmt.Errorf("authentication required: %w", err)
	}

	meterVal := ""
	if meter != nil {
		meterVal = *meter
	}

	amountVal := int64(0)
	if amount != nil {
		amountVal = int64(*amount)
	}

	if err := r.planService.CheckCreditAvailable(ctx, companyID, meterVal, amountVal); err != nil {
		if errors.Is(err, service.ErrInsufficientCredit) || errors.Is(err, service.ErrNoAccount) {
			return false, nil
		}
		return false, fmt.Errorf("failed to check credits: %w", err)
	}

	return true, nil
}

// Error is the resolver for the error field on StepHistory.
// Extracts error message from metadata JSON when status is "failed" or "error".
// Only reads from metadata field (SDK-controlled), not context (customer data).
func (r *stepHistoryResolver) Error(ctx context.Context, obj *models.StepHistory) (*string, error) {
	// Only extract error for failed/error statuses
	if obj.Status != "failed" && obj.Status != "error" {
		return nil, nil
	}

	// Extract from metadata field (SDK stores error here)
	// We don't read from context as that contains customer data
	if obj.Metadata == "" {
		return nil, nil
	}

	var metadataData map[string]interface{}
	if err := json.Unmarshal([]byte(obj.Metadata), &metadataData); err != nil {
		return nil, nil
	}

	errorVal, ok := metadataData["error"]
	if !ok {
		return nil, nil
	}

	// Convert error value to string
	switch v := errorVal.(type) {
	case string:
		return &v, nil
	case map[string]interface{}:
		// If error is an object, stringify it
		errorJSON, err := json.Marshal(v)
		if err != nil {
			return nil, nil
		}
		errorStr := string(errorJSON)
		return &errorStr, nil
	default:
		// For other types, convert to string
		errorStr := fmt.Sprintf("%v", v)
		return &errorStr, nil
	}
}

// FirstSeenAt is the resolver for the firstSeenAt field.
func (r *stepStateInfoResolver) FirstSeenAt(ctx context.Context, obj *models.StepStateInfo) (string, error) {
	return obj.FirstSeenAt.Format(time.RFC3339Nano), nil
}

// LastUpdatedAt is the resolver for the lastUpdatedAt field.
func (r *stepStateInfoResolver) LastUpdatedAt(ctx context.Context, obj *models.StepStateInfo) (string, error) {
	return obj.LastUpdatedAt.Format(time.RFC3339Nano), nil
}

// Hash is the resolver for the hash field in StepStateInfo
// Returns the cryptographic hash for the step
func (r *stepStateInfoResolver) Hash(ctx context.Context, obj *models.StepStateInfo) (*string, error) {
	hash, _, err := r.activityRepo.GetStepHashes(ctx, obj.ThreadID, obj.StepName, obj.IdempotencyKey)
	if err != nil {
		return nil, fmt.Errorf("failed to get step hash: %w", err)
	}
	if hash == "" {
		return nil, nil
	}
	return &hash, nil
}

// PrevHash is the resolver for the prevHash field in StepStateInfo
// Returns the previous hash in the chain for the step
func (r *stepStateInfoResolver) PrevHash(ctx context.Context, obj *models.StepStateInfo) (*string, error) {
	_, prevHash, err := r.activityRepo.GetStepHashes(ctx, obj.ThreadID, obj.StepName, obj.IdempotencyKey)
	if err != nil {
		return nil, fmt.Errorf("failed to get step prevHash: %w", err)
	}
	if prevHash == "" {
		return nil, nil
	}
	return &prevHash, nil
}

// Verified is the resolver for the verified field.
func (r *stepStateInfoResolver) Verified(ctx context.Context, obj *models.StepStateInfo) (*bool, error) {
	// Check if verification result is already cached in context
	type verificationResult struct {
		verified bool
		errMsg   string
	}
	cacheKey := fmt.Sprintf("step_verification:%s:%s:%s", obj.ThreadID, obj.StepName, obj.IdempotencyKey)

	if cached := ctx.Value(cacheKey); cached != nil {
		result := cached.(verificationResult)
		return &result.verified, nil
	}

	// Compute and cache verification result
	verified, errMsg, err := r.activityRepo.VerifyStepHash(ctx, obj.ThreadID, obj.StepName, obj.IdempotencyKey)
	if err != nil {
		return nil, err
	}

	// Cache result for VerificationError resolver
	ctx = context.WithValue(ctx, cacheKey, verificationResult{verified: verified, errMsg: errMsg})

	return &verified, nil
}

// VerificationError is the resolver for the verificationError field.
func (r *stepStateInfoResolver) VerificationError(ctx context.Context, obj *models.StepStateInfo) (*string, error) {
	// Check if verification result is already cached in context
	type verificationResult struct {
		verified bool
		errMsg   string
	}
	cacheKey := fmt.Sprintf("step_verification:%s:%s:%s", obj.ThreadID, obj.StepName, obj.IdempotencyKey)

	if cached := ctx.Value(cacheKey); cached != nil {
		result := cached.(verificationResult)
		if result.errMsg == "" {
			return nil, nil
		}
		return &result.errMsg, nil
	}

	// Compute and cache verification result
	verified, errMsg, err := r.activityRepo.VerifyStepHash(ctx, obj.ThreadID, obj.StepName, obj.IdempotencyKey)
	if err != nil {
		return nil, err
	}

	// Cache result for Verified resolver
	ctx = context.WithValue(ctx, cacheKey, verificationResult{verified: verified, errMsg: errMsg})

	if errMsg == "" {
		return nil, nil
	}
	return &errMsg, nil
}

// History is the resolver for the history field.
func (r *stepStateInfoResolver) History(ctx context.Context, obj *models.StepStateInfo, limit *int, offset *int, startAt *string, endAt *string, activityType *string, actor *string) ([]*models.StepHistory, error) {
	// Get user info from context for permission check
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Enforce hard caps on pagination limits
	limitVal := EnforceLimit(limit, MaxHistoryPerQuery, 100)
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}

	// Use step name as identifier (will get all idempotency keys for this step)
	// Users can call this on a specific step instance to get that instance's history
	stepIdentifier := obj.StepName
	if obj.IdempotencyKey != "" {
		stepIdentifier = fmt.Sprintf("%s:%s", obj.StepName, obj.IdempotencyKey)
	}

	// Get step history from PostgreSQL with permission check
	history, err := r.stepStateRepo.GetStepHistoryWithPermissionCheck(ctx, obj.ThreadID, companyID, stepIdentifier, limitVal, offsetVal, startAt, endAt, activityType, actor)
	if err != nil {
		return nil, fmt.Errorf("failed to get step history: %w", err)
	}

	// Return empty array if no history found (better UX than error)
	if history == nil {
		return []*models.StepHistory{}, nil
	}

	// Convert slice of values to slice of pointers for GraphQL
	var historyPtrs []*models.StepHistory
	for i := range history {
		historyPtrs = append(historyPtrs, &history[i])
	}

	return historyPtrs, nil
}

// SubSteps resolver for StepStateInfo.subSteps field
func (r *stepStateInfoResolver) SubSteps(ctx context.Context, obj *models.StepStateInfo) ([]*models.SubStep, error) {
	// Get sub-steps from database using latestStepID
	subSteps, err := r.Resolver.subStepRepo.GetSubStepsByStepID(ctx, obj.LatestStepID)
	if err != nil {
		return nil, err
	}

	// Return sub-steps directly
	return subSteps, nil
}

// Payload is the resolver for the payload field.
func (r *subStepResolver) Payload(ctx context.Context, obj *models.SubStep) (*string, error) {
	if obj.Payload == nil {
		return nil, nil
	}
	// Convert payload to JSON string
	payloadJSON, err := json.Marshal(obj.Payload)
	if err != nil {
		return nil, err
	}
	payloadStr := string(payloadJSON)
	return &payloadStr, nil
}

// RecordedAt is the resolver for the recordedAt field.
func (r *subStepResolver) RecordedAt(ctx context.Context, obj *models.SubStep) (string, error) {
	return obj.RecordedAt.Format(time.RFC3339Nano), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *subStepResolver) CreatedAt(ctx context.Context, obj *models.SubStep) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339Nano), nil
}

// Status is the resolver for the status field.
func (r *threadResolver) Status(ctx context.Context, obj *models.Thread) (string, error) {
	status := string(obj.Status)
	return status, nil
}

// Refs is the resolver for the refs field.
func (r *threadResolver) Refs(ctx context.Context, obj *models.Thread) (*string, error) {
	if obj.Refs == nil {
		return nil, nil
	}
	refsJSON, err := json.Marshal(obj.Refs)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal refs: %w", err)
	}
	refsStr := string(refsJSON)
	return &refsStr, nil
}

// StartedAt is the resolver for the startedAt field.
func (r *threadResolver) StartedAt(ctx context.Context, obj *models.Thread) (*string, error) {
	startedAt := obj.StartedAt.Format(time.RFC3339Nano)
	return &startedAt, nil
}

// CompletedAt is the resolver for the completedAt field.
func (r *threadResolver) CompletedAt(ctx context.Context, obj *models.Thread) (*string, error) {
	if obj.CompletedAt == nil {
		return nil, nil
	}
	completedAt := obj.CompletedAt.Format(time.RFC3339Nano)
	return &completedAt, nil
}

// Steps is the resolver for the steps field.
func (r *threadResolver) Steps(ctx context.Context, obj *models.Thread, stepName *string, idempotencyKey *string, status *string) ([]*models.StepStateInfo, error) {
	// Get user info from context
	ownerID, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Check if steps are already cached from batch loading
	if cachedSteps, found := getCachedSteps(ctx, obj.ID); found {
		allSteps, ok := cachedSteps.([]*models.StepStateInfo)
		if !ok {
			return nil, fmt.Errorf("invalid cached steps type")
		}

		// Apply filters in memory (batch-loaded steps don't have filters applied)
		steps := make([]*models.StepStateInfo, 0)
		for _, step := range allSteps {
			if stepName != nil && step.StepName != *stepName {
				continue
			}
			if idempotencyKey != nil && *idempotencyKey != "" && step.IdempotencyKey != *idempotencyKey {
				continue
			}
			if status != nil && *status != "" && step.Status != *status {
				continue
			}
			steps = append(steps, step)
		}
		return steps, nil
	}

	// Hot path: Try Valkey first with permission check
	if r.accessRepo != nil {
		permCheck, err := r.accessRepo.CheckUserReadPermission(ctx, obj.ID, ownerID)
		if err == nil && permCheck != nil && permCheck.HasAccess {
			steps, err := r.stepStateRepo.GetStepsWithPermissionCheck(ctx, obj.ID, ownerID, permCheck, stepName, idempotencyKey, status)
			if err == nil {
				return steps, nil
			}
			// Fall through to PostgreSQL on error
		}
	}

	// Cold path: PostgreSQL with SQL-level permission check
	steps, err := r.stepStatePostgres.GetStepsWithPermissionCheck(ctx, obj.ID, companyID, stepName, idempotencyKey, status)
	if err != nil {
		return nil, fmt.Errorf("failed to list steps for thread %s: %w", obj.ID, err)
	}

	return steps, nil
}

// ValidationResults is the resolver for the validationResults field.
func (r *threadResolver) ValidationResults(ctx context.Context, obj *models.Thread, options *models.ValidationQueryOptions) ([]*models.ValidationResultInfo, error) {
	// Get user info from context
	ownerID, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Hot path: Try Valkey first with permission check
	if r.accessRepo != nil {
		permCheck, err := r.accessRepo.CheckUserReadPermission(ctx, obj.ID, ownerID)
		if err == nil && permCheck != nil && permCheck.HasAccess {
			results, err := r.validationRepo.GetValidationResultsWithPermissionCheck(ctx, obj.ID, ownerID, permCheck, options)
			if err == nil {
				return results, nil
			}
			// Fall through to PostgreSQL on error
		}
	}

	// Cold path: PostgreSQL with SQL-level permission check
	postgresValidationRepo := r.validationRepo.GetPostgresRepo()
	if postgresValidationRepo == nil {
		return nil, fmt.Errorf("no PostgreSQL repository configured for validation queries")
	}

	return postgresValidationRepo.GetValidationResultsWithPermissionCheck(ctx, obj.ID, companyID, options)
}

// NotificationSummary is the resolver for the notificationSummary field.
func (r *threadResolver) NotificationSummary(ctx context.Context, obj *models.Thread) (*models.NotificationSummary, error) {
	// Permission already checked by parent Thread query
	// If we got here, user has access to the thread

	// Get notification summary (lightweight query)
	if r.notificationRepo == nil {
		return nil, fmt.Errorf("no notification repository configured")
	}

	return r.notificationRepo.GetNotificationSummary(ctx, obj.ID)
}

// Notifications is the resolver for the notifications field.
func (r *threadResolver) Notifications(ctx context.Context, obj *models.Thread, options *models.ThreadNotificationQueryOptions) ([]*models.ThreadNotification, error) {
	// Permission already checked by parent Thread query
	// If we got here, user has access to the thread

	// Get postgres notification repository
	postgresNotificationRepo := r.notificationRepo
	if postgresNotificationRepo == nil {
		return nil, fmt.Errorf("no notification repository configured")
	}

	// Set threadID in options if not already set
	if options == nil {
		options = &models.ThreadNotificationQueryOptions{
			ThreadID: obj.ID,
		}
	} else if options.ThreadID == "" {
		options.ThreadID = obj.ID
	}

	// Query notifications
	return postgresNotificationRepo.GetThreadNotifications(ctx, obj.ID, options)
}

// ThreadChain is the resolver for the threadChain field on Thread type.
func (r *threadResolver) ThreadChain(ctx context.Context, obj *models.Thread, maxDepth *int) ([]*models.Thread, error) {
	// Get user info from context
	_, companyID, _, err := getUserInfoFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Set default max depth
	depthVal := 3
	if maxDepth != nil {
		depthVal = *maxDepth
		if depthVal <= 0 || depthVal > 10 {
			return nil, fmt.Errorf("maxDepth must be between 1 and 10")
		}
	}

	// Get postgres repository
	postgresRepo := r.threadRepo.GetPostgresRepo()
	if postgresRepo == nil {
		return nil, apperrors.NewInternalError("Postgres repository not available", nil)
	}

	// SQL-level permission check with recursive CTE
	// Permission check happens at each level of the chain
	threads, err := postgresRepo.GetThreadChainWithPermissionCheck(ctx, obj.ID, companyID, &depthVal)
	if err != nil {
		return nil, apperrors.NewInternalError("Failed to query thread chain", err)
	}

	return threads, nil
}

// HashChainVerified is the resolver for the hashChainVerified field.
func (r *threadResolver) HashChainVerified(ctx context.Context, obj *models.Thread) (*bool, error) {
	// Only compute when explicitly requested in GraphQL query
	status, err := r.activityRepo.VerifyActivityChain(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return &status.Verified, nil
}

// HashChainStatus is the resolver for the hashChainStatus field.
func (r *threadResolver) HashChainStatus(ctx context.Context, obj *models.Thread) (*models.HashChainStatus, error) {
	// Return detailed verification status
	return r.activityRepo.VerifyActivityChain(ctx, obj.ID)
}

// Details is the resolver for the details field.
func (r *threadNotificationResolver) Details(ctx context.Context, obj *models.ThreadNotification) (*string, error) {
	// Return details as JSON string
	if obj.Details == nil || len(obj.Details) == 0 {
		emptyJSON := "{}"
		return &emptyJSON, nil
	}

	detailsJSON, err := json.Marshal(obj.Details)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal details: %w", err)
	}

	result := string(detailsJSON)
	return &result, nil
}

// Timestamp is the resolver for the timestamp field.
func (r *threadNotificationResolver) Timestamp(ctx context.Context, obj *models.ThreadNotification) (string, error) {
	// Format timestamp as RFC3339 string
	return obj.Timestamp.Format(time.RFC3339Nano), nil
}

// Timestamp is the resolver for the timestamp field.
func (r *validationResultInfoResolver) Timestamp(ctx context.Context, obj *models.ValidationResultInfo) (string, error) {
	return obj.Timestamp.Format(time.RFC3339Nano), nil
}

// Graph returns generated.GraphResolver implementation.
func (r *Resolver) Graph() generated.GraphResolver { return &graphResolver{r} }

// GraphNode returns generated.GraphNodeResolver implementation.
func (r *Resolver) GraphNode() generated.GraphNodeResolver { return &graphNodeResolver{r} }

// HashChainStatus returns generated.HashChainStatusResolver implementation.
func (r *Resolver) HashChainStatus() generated.HashChainStatusResolver {
	return &hashChainStatusResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// NotificationConfig returns generated.NotificationConfigResolver implementation.
func (r *Resolver) NotificationConfig() generated.NotificationConfigResolver {
	return &notificationConfigResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// StepHistory returns generated.StepHistoryResolver implementation.
func (r *Resolver) StepHistory() generated.StepHistoryResolver { return &stepHistoryResolver{r} }

// StepStateInfo returns generated.StepStateInfoResolver implementation.
func (r *Resolver) StepStateInfo() generated.StepStateInfoResolver { return &stepStateInfoResolver{r} }

// SubStep returns generated.SubStepResolver implementation.
func (r *Resolver) SubStep() generated.SubStepResolver { return &subStepResolver{r} }

// Thread returns generated.ThreadResolver implementation.
func (r *Resolver) Thread() generated.ThreadResolver { return &threadResolver{r} }

// ThreadNotification returns generated.ThreadNotificationResolver implementation.
func (r *Resolver) ThreadNotification() generated.ThreadNotificationResolver {
	return &threadNotificationResolver{r}
}

// ValidationResultInfo returns generated.ValidationResultInfoResolver implementation.
func (r *Resolver) ValidationResultInfo() generated.ValidationResultInfoResolver {
	return &validationResultInfoResolver{r}
}

type graphResolver struct{ *Resolver }
type graphNodeResolver struct{ *Resolver }
type hashChainStatusResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type notificationConfigResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type stepHistoryResolver struct{ *Resolver }
type stepStateInfoResolver struct{ *Resolver }
type subStepResolver struct{ *Resolver }
type threadResolver struct{ *Resolver }
type threadNotificationResolver struct{ *Resolver }
type validationResultInfoResolver struct{ *Resolver }
