// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"
	models "threadify-go/api/internal/models"
	service "threadify-go/api/internal/service"
	auth "threadify-go/shared/auth"
	models0 "threadify-go/shared/models"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockAuthService) ForgotPassword(ctx context.Context, req *models.ForgotPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockAuthServiceMockRecorder) ForgotPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockAuthService)(nil).ForgotPassword), ctx, req)
}

// GetUserRoles mocks base method.
func (m *MockAuthService) GetUserRoles(ctx context.Context, userID, principalType string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID, principalType)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAuthServiceMockRecorder) GetUserRoles(ctx, userID, principalType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAuthService)(nil).GetUserRoles), ctx, userID, principalType)
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, req *models.LoginRequest, clientIP string) (*models.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, clientIP)
	ret0, _ := ret[0].(*models.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, req, clientIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, req, clientIP)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, token)
}

// ResendVerificationEmail mocks base method.
func (m *MockAuthService) ResendVerificationEmail(ctx context.Context, req *models.ResendVerificationEmailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerificationEmail", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendVerificationEmail indicates an expected call of ResendVerificationEmail.
func (mr *MockAuthServiceMockRecorder) ResendVerificationEmail(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerificationEmail", reflect.TypeOf((*MockAuthService)(nil).ResendVerificationEmail), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockAuthService) ResetPassword(ctx context.Context, req *models.ResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthServiceMockRecorder) ResetPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthService)(nil).ResetPassword), ctx, req)
}

// Signup mocks base method.
func (m *MockAuthService) Signup(ctx context.Context, req *models.SignupRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockAuthServiceMockRecorder) Signup(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockAuthService)(nil).Signup), ctx, req)
}

// VerifyEmail mocks base method.
func (m *MockAuthService) VerifyEmail(ctx context.Context, req *models.VerifyEmailRequest) (*models.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, req)
	ret0, _ := ret[0].(*models.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockAuthServiceMockRecorder) VerifyEmail(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockAuthService)(nil).VerifyEmail), ctx, req)
}

// VerifyToken mocks base method.
func (m *MockAuthService) VerifyToken(ctx context.Context, tokenString string) (*auth.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, tokenString)
	ret0, _ := ret[0].(*auth.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthServiceMockRecorder) VerifyToken(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthService)(nil).VerifyToken), ctx, tokenString)
}

// MockAPIKeyService is a mock of APIKeyService interface.
type MockAPIKeyService struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyServiceMockRecorder
}

// MockAPIKeyServiceMockRecorder is the mock recorder for MockAPIKeyService.
type MockAPIKeyServiceMockRecorder struct {
	mock *MockAPIKeyService
}

// NewMockAPIKeyService creates a new mock instance.
func NewMockAPIKeyService(ctrl *gomock.Controller) *MockAPIKeyService {
	mock := &MockAPIKeyService{ctrl: ctrl}
	mock.recorder = &MockAPIKeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyService) EXPECT() *MockAPIKeyServiceMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockAPIKeyService) CreateAPIKey(ctx context.Context, userID, companyID string, req *service.CreateAPIKeyRequest) (*service.CreateAPIKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, userID, companyID, req)
	ret0, _ := ret[0].(*service.CreateAPIKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) CreateAPIKey(ctx, userID, companyID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).CreateAPIKey), ctx, userID, companyID, req)
}

// ListAPIKeys mocks base method.
func (m *MockAPIKeyService) ListAPIKeys(ctx context.Context, companyID string) ([]*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeys", ctx, companyID)
	ret0, _ := ret[0].([]*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIKeys indicates an expected call of ListAPIKeys.
func (mr *MockAPIKeyServiceMockRecorder) ListAPIKeys(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeys", reflect.TypeOf((*MockAPIKeyService)(nil).ListAPIKeys), ctx, companyID)
}

// RevokeAPIKey mocks base method.
func (m *MockAPIKeyService) RevokeAPIKey(ctx context.Context, keyID, companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIKey", ctx, keyID, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAPIKey indicates an expected call of RevokeAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) RevokeAPIKey(ctx, keyID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).RevokeAPIKey), ctx, keyID, companyID)
}

// ValidateAPIKey mocks base method.
func (m *MockAPIKeyService) ValidateAPIKey(ctx context.Context, key string) (*models.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAPIKey", ctx, key)
	ret0, _ := ret[0].(*models.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAPIKey indicates an expected call of ValidateAPIKey.
func (mr *MockAPIKeyServiceMockRecorder) ValidateAPIKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAPIKey", reflect.TypeOf((*MockAPIKeyService)(nil).ValidateAPIKey), ctx, key)
}

// MockTeamInvitationService is a mock of TeamInvitationService interface.
type MockTeamInvitationService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamInvitationServiceMockRecorder
}

// MockTeamInvitationServiceMockRecorder is the mock recorder for MockTeamInvitationService.
type MockTeamInvitationServiceMockRecorder struct {
	mock *MockTeamInvitationService
}

// NewMockTeamInvitationService creates a new mock instance.
func NewMockTeamInvitationService(ctrl *gomock.Controller) *MockTeamInvitationService {
	mock := &MockTeamInvitationService{ctrl: ctrl}
	mock.recorder = &MockTeamInvitationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamInvitationService) EXPECT() *MockTeamInvitationServiceMockRecorder {
	return m.recorder
}

// CancelInvitation mocks base method.
func (m *MockTeamInvitationService) CancelInvitation(ctx context.Context, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInvitation", ctx, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelInvitation indicates an expected call of CancelInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) CancelInvitation(ctx, invitationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).CancelInvitation), ctx, invitationID)
}

// GetByCompanyAndEmail mocks base method.
func (m *MockTeamInvitationService) GetByCompanyAndEmail(ctx context.Context, companyID, email string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCompanyAndEmail", ctx, companyID, email)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCompanyAndEmail indicates an expected call of GetByCompanyAndEmail.
func (mr *MockTeamInvitationServiceMockRecorder) GetByCompanyAndEmail(ctx, companyID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCompanyAndEmail", reflect.TypeOf((*MockTeamInvitationService)(nil).GetByCompanyAndEmail), ctx, companyID, email)
}

// GetByID mocks base method.
func (m *MockTeamInvitationService) GetByID(ctx context.Context, invitationID string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, invitationID)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeamInvitationServiceMockRecorder) GetByID(ctx, invitationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeamInvitationService)(nil).GetByID), ctx, invitationID)
}

// ListByCompany mocks base method.
func (m *MockTeamInvitationService) ListByCompany(ctx context.Context, companyID string) ([]*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCompany", ctx, companyID)
	ret0, _ := ret[0].([]*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCompany indicates an expected call of ListByCompany.
func (mr *MockTeamInvitationServiceMockRecorder) ListByCompany(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCompany", reflect.TypeOf((*MockTeamInvitationService)(nil).ListByCompany), ctx, companyID)
}

// MarkAccepted mocks base method.
func (m *MockTeamInvitationService) MarkAccepted(ctx context.Context, invitationID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAccepted", ctx, invitationID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAccepted indicates an expected call of MarkAccepted.
func (mr *MockTeamInvitationServiceMockRecorder) MarkAccepted(ctx, invitationID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAccepted", reflect.TypeOf((*MockTeamInvitationService)(nil).MarkAccepted), ctx, invitationID, userID)
}

// RefreshInvitation mocks base method.
func (m *MockTeamInvitationService) RefreshInvitation(ctx context.Context, invitation *models.TeamInvitation, duration time.Duration) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshInvitation", ctx, invitation, duration)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshInvitation indicates an expected call of RefreshInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) RefreshInvitation(ctx, invitation, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).RefreshInvitation), ctx, invitation, duration)
}

// SendInvitation mocks base method.
func (m *MockTeamInvitationService) SendInvitation(ctx context.Context, companyID, email, role, invitedBy string, expiryDuration time.Duration) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvitation", ctx, companyID, email, role, invitedBy, expiryDuration)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendInvitation indicates an expected call of SendInvitation.
func (mr *MockTeamInvitationServiceMockRecorder) SendInvitation(ctx, companyID, email, role, invitedBy, expiryDuration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvitation", reflect.TypeOf((*MockTeamInvitationService)(nil).SendInvitation), ctx, companyID, email, role, invitedBy, expiryDuration)
}

// ValidateToken mocks base method.
func (m *MockTeamInvitationService) ValidateToken(ctx context.Context, token string) (*models.TeamInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(*models.TeamInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTeamInvitationServiceMockRecorder) ValidateToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTeamInvitationService)(nil).ValidateToken), ctx, token)
}

// MockAgentService is a mock of AgentService interface.
type MockAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServiceMockRecorder
}

// MockAgentServiceMockRecorder is the mock recorder for MockAgentService.
type MockAgentServiceMockRecorder struct {
	mock *MockAgentService
}

// NewMockAgentService creates a new mock instance.
func NewMockAgentService(ctrl *gomock.Controller) *MockAgentService {
	mock := &MockAgentService{ctrl: ctrl}
	mock.recorder = &MockAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentService) EXPECT() *MockAgentServiceMockRecorder {
	return m.recorder
}

// ChatStream mocks base method.
func (m *MockAgentService) ChatStream(ctx context.Context, authHeader, userID, companyID, conversationID, message, skill string, onEvent service.StreamHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, authHeader, userID, companyID, conversationID, message, skill, onEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockAgentServiceMockRecorder) ChatStream(ctx, authHeader, userID, companyID, conversationID, message, skill, onEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockAgentService)(nil).ChatStream), ctx, authHeader, userID, companyID, conversationID, message, skill, onEvent)
}

// CheckCredits mocks base method.
func (m *MockAgentService) CheckCredits(ctx context.Context, authHeader string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCredits", ctx, authHeader)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCredits indicates an expected call of CheckCredits.
func (mr *MockAgentServiceMockRecorder) CheckCredits(ctx, authHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCredits", reflect.TypeOf((*MockAgentService)(nil).CheckCredits), ctx, authHeader)
}

// ContinueConversation mocks base method.
func (m *MockAgentService) ContinueConversation(ctx context.Context, userID, companyID, parentConvID string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContinueConversation", ctx, userID, companyID, parentConvID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ContinueConversation indicates an expected call of ContinueConversation.
func (mr *MockAgentServiceMockRecorder) ContinueConversation(ctx, userID, companyID, parentConvID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContinueConversation", reflect.TypeOf((*MockAgentService)(nil).ContinueConversation), ctx, userID, companyID, parentConvID)
}

// DeleteConversation mocks base method.
func (m *MockAgentService) DeleteConversation(ctx context.Context, companyID, convID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversation", ctx, companyID, convID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversation indicates an expected call of DeleteConversation.
func (mr *MockAgentServiceMockRecorder) DeleteConversation(ctx, companyID, convID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversation", reflect.TypeOf((*MockAgentService)(nil).DeleteConversation), ctx, companyID, convID)
}

// GetConversations mocks base method.
func (m *MockAgentService) GetConversations(ctx context.Context, companyID string) ([]models.AgentConversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversations", ctx, companyID)
	ret0, _ := ret[0].([]models.AgentConversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversations indicates an expected call of GetConversations.
func (mr *MockAgentServiceMockRecorder) GetConversations(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversations", reflect.TypeOf((*MockAgentService)(nil).GetConversations), ctx, companyID)
}

// GetMessagesForUser mocks base method.
func (m *MockAgentService) GetMessagesForUser(ctx context.Context, companyID, convID string) ([]*models.AgentMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesForUser", ctx, companyID, convID)
	ret0, _ := ret[0].([]*models.AgentMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesForUser indicates an expected call of GetMessagesForUser.
func (mr *MockAgentServiceMockRecorder) GetMessagesForUser(ctx, companyID, convID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesForUser", reflect.TypeOf((*MockAgentService)(nil).GetMessagesForUser), ctx, companyID, convID)
}

// MockServiceAccountService is a mock of ServiceAccountService interface.
type MockServiceAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountServiceMockRecorder
}

// MockServiceAccountServiceMockRecorder is the mock recorder for MockServiceAccountService.
type MockServiceAccountServiceMockRecorder struct {
	mock *MockServiceAccountService
}

// NewMockServiceAccountService creates a new mock instance.
func NewMockServiceAccountService(ctrl *gomock.Controller) *MockServiceAccountService {
	mock := &MockServiceAccountService{ctrl: ctrl}
	mock.recorder = &MockServiceAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountService) EXPECT() *MockServiceAccountServiceMockRecorder {
	return m.recorder
}

// CreateServiceAccount mocks base method.
func (m *MockServiceAccountService) CreateServiceAccount(ctx context.Context, companyID, createdBy string, req *service.CreateServiceAccountRequest) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", ctx, companyID, createdBy, req)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) CreateServiceAccount(ctx, companyID, createdBy, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).CreateServiceAccount), ctx, companyID, createdBy, req)
}

// DeleteServiceAccount mocks base method.
func (m *MockServiceAccountService) DeleteServiceAccount(ctx context.Context, id, companyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceAccount", ctx, id, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) DeleteServiceAccount(ctx, id, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).DeleteServiceAccount), ctx, id, companyID)
}

// GetServiceAccount mocks base method.
func (m *MockServiceAccountService) GetServiceAccount(ctx context.Context, id, companyID string) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccount", ctx, id, companyID)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) GetServiceAccount(ctx, id, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).GetServiceAccount), ctx, id, companyID)
}

// ListServiceAccounts mocks base method.
func (m *MockServiceAccountService) ListServiceAccounts(ctx context.Context, companyID string) ([]*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccounts", ctx, companyID)
	ret0, _ := ret[0].([]*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccounts indicates an expected call of ListServiceAccounts.
func (mr *MockServiceAccountServiceMockRecorder) ListServiceAccounts(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccounts", reflect.TypeOf((*MockServiceAccountService)(nil).ListServiceAccounts), ctx, companyID)
}

// UpdateServiceAccount mocks base method.
func (m *MockServiceAccountService) UpdateServiceAccount(ctx context.Context, id, companyID string, req *service.UpdateServiceAccountRequest) (*models.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceAccount", ctx, id, companyID, req)
	ret0, _ := ret[0].(*models.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceAccount indicates an expected call of UpdateServiceAccount.
func (mr *MockServiceAccountServiceMockRecorder) UpdateServiceAccount(ctx, id, companyID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceAccount", reflect.TypeOf((*MockServiceAccountService)(nil).UpdateServiceAccount), ctx, id, companyID, req)
}

// MockEntityProfileTypeService is a mock of EntityProfileTypeService interface.
type MockEntityProfileTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockEntityProfileTypeServiceMockRecorder
}

// MockEntityProfileTypeServiceMockRecorder is the mock recorder for MockEntityProfileTypeService.
type MockEntityProfileTypeServiceMockRecorder struct {
	mock *MockEntityProfileTypeService
}

// NewMockEntityProfileTypeService creates a new mock instance.
func NewMockEntityProfileTypeService(ctrl *gomock.Controller) *MockEntityProfileTypeService {
	mock := &MockEntityProfileTypeService{ctrl: ctrl}
	mock.recorder = &MockEntityProfileTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityProfileTypeService) EXPECT() *MockEntityProfileTypeServiceMockRecorder {
	return m.recorder
}

// ArchiveEntityProfileType mocks base method.
func (m *MockEntityProfileTypeService) ArchiveEntityProfileType(ctx context.Context, companyID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveEntityProfileType", ctx, companyID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveEntityProfileType indicates an expected call of ArchiveEntityProfileType.
func (mr *MockEntityProfileTypeServiceMockRecorder) ArchiveEntityProfileType(ctx, companyID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveEntityProfileType", reflect.TypeOf((*MockEntityProfileTypeService)(nil).ArchiveEntityProfileType), ctx, companyID, id)
}

// CreateEntityProfileType mocks base method.
func (m *MockEntityProfileTypeService) CreateEntityProfileType(ctx context.Context, companyID string, req *models.CreateEntityProfileTypeRequest) (*models0.EntityProfileType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntityProfileType", ctx, companyID, req)
	ret0, _ := ret[0].(*models0.EntityProfileType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntityProfileType indicates an expected call of CreateEntityProfileType.
func (mr *MockEntityProfileTypeServiceMockRecorder) CreateEntityProfileType(ctx, companyID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntityProfileType", reflect.TypeOf((*MockEntityProfileTypeService)(nil).CreateEntityProfileType), ctx, companyID, req)
}

// ListEntityProfileTypes mocks base method.
func (m *MockEntityProfileTypeService) ListEntityProfileTypes(ctx context.Context, companyID string) ([]*models0.EntityProfileType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntityProfileTypes", ctx, companyID)
	ret0, _ := ret[0].([]*models0.EntityProfileType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntityProfileTypes indicates an expected call of ListEntityProfileTypes.
func (mr *MockEntityProfileTypeServiceMockRecorder) ListEntityProfileTypes(ctx, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntityProfileTypes", reflect.TypeOf((*MockEntityProfileTypeService)(nil).ListEntityProfileTypes), ctx, companyID)
}

// UpdateEntityProfileType mocks base method.
func (m *MockEntityProfileTypeService) UpdateEntityProfileType(ctx context.Context, companyID, id string, req *models.UpdateEntityProfileTypeRequest) (*models0.EntityProfileType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntityProfileType", ctx, companyID, id, req)
	ret0, _ := ret[0].(*models0.EntityProfileType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntityProfileType indicates an expected call of UpdateEntityProfileType.
func (mr *MockEntityProfileTypeServiceMockRecorder) UpdateEntityProfileType(ctx, companyID, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntityProfileType", reflect.TypeOf((*MockEntityProfileTypeService)(nil).UpdateEntityProfileType), ctx, companyID, id, req)
}
