# docker-compose.network.yml
version: '3'

services:
  network-creator:
    image: alpine:latest
    command: echo "Network created"
    networks:
      - threadify-network
    deploy:
      restart_policy:
        condition: none

networks:
  threadify-network:
    name: threadify-network
    driver: bridge