// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/shared/management/domain (interfaces: ServiceAccountRepository)

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"
	domain "threadify-go/shared/management/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceAccountRepository is a mock of ServiceAccountRepository interface.
type MockServiceAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountRepositoryMockRecorder
}

// MockServiceAccountRepositoryMockRecorder is the mock recorder for MockServiceAccountRepository.
type MockServiceAccountRepositoryMockRecorder struct {
	mock *MockServiceAccountRepository
}

// NewMockServiceAccountRepository creates a new mock instance.
func NewMockServiceAccountRepository(ctrl *gomock.Controller) *MockServiceAccountRepository {
	mock := &MockServiceAccountRepository{ctrl: ctrl}
	mock.recorder = &MockServiceAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountRepository) EXPECT() *MockServiceAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceAccountRepository) Create(arg0 context.Context, arg1 *domain.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockServiceAccountRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceAccountRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockServiceAccountRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceAccountRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceAccountRepository)(nil).Delete), arg0, arg1)
}

// FindByCompanyID mocks base method.
func (m *MockServiceAccountRepository) FindByCompanyID(arg0 context.Context, arg1 string) ([]*domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCompanyID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCompanyID indicates an expected call of FindByCompanyID.
func (mr *MockServiceAccountRepositoryMockRecorder) FindByCompanyID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCompanyID", reflect.TypeOf((*MockServiceAccountRepository)(nil).FindByCompanyID), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockServiceAccountRepository) FindByID(arg0 context.Context, arg1 string) (*domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockServiceAccountRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockServiceAccountRepository)(nil).FindByID), arg0, arg1)
}

// IsServiceAccountActive mocks base method.
func (m *MockServiceAccountRepository) IsServiceAccountActive(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsServiceAccountActive", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsServiceAccountActive indicates an expected call of IsServiceAccountActive.
func (mr *MockServiceAccountRepositoryMockRecorder) IsServiceAccountActive(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsServiceAccountActive", reflect.TypeOf((*MockServiceAccountRepository)(nil).IsServiceAccountActive), arg0, arg1)
}

// Update mocks base method.
func (m *MockServiceAccountRepository) Update(arg0 context.Context, arg1 *domain.ServiceAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServiceAccountRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceAccountRepository)(nil).Update), arg0, arg1)
}

// UpdateLastUsed mocks base method.
func (m *MockServiceAccountRepository) UpdateLastUsed(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockServiceAccountRepositoryMockRecorder) UpdateLastUsed(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockServiceAccountRepository)(nil).UpdateLastUsed), arg0, arg1)
}
