// Code generated by MockGen. DO NOT EDIT.
// Source: threadify-go/api/internal/ports (interfaces: PermissionLoader)

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPermissionLoader is a mock of PermissionLoader interface.
type MockPermissionLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionLoaderMockRecorder
}

// MockPermissionLoaderMockRecorder is the mock recorder for MockPermissionLoader.
type MockPermissionLoaderMockRecorder struct {
	mock *MockPermissionLoader
}

// NewMockPermissionLoader creates a new mock instance.
func NewMockPermissionLoader(ctrl *gomock.Controller) *MockPermissionLoader {
	mock := &MockPermissionLoader{ctrl: ctrl}
	mock.recorder = &MockPermissionLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionLoader) EXPECT() *MockPermissionLoaderMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockPermissionLoader) CheckPermission(arg0 []string, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPermissionLoaderMockRecorder) CheckPermission(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPermissionLoader)(nil).CheckPermission), arg0, arg1)
}

// GetPermissionsForRoles mocks base method.
func (m *MockPermissionLoader) GetPermissionsForRoles(arg0 []string, arg1 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsForRoles", arg0, arg1)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetPermissionsForRoles indicates an expected call of GetPermissionsForRoles.
func (mr *MockPermissionLoaderMockRecorder) GetPermissionsForRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsForRoles", reflect.TypeOf((*MockPermissionLoader)(nil).GetPermissionsForRoles), arg0, arg1)
}
